module.exports =
  oldSchool:
    chagrin: ":P"
    frown: ":("
    sheep: ":}"
    smile: ":)"
    winkle: ";)"
  unicode:
    "smile": "😄"
    "smiley": "😃"
    "grinning": "😀"
    "blush": "😊"
    "relaxed": "☺️"
    "wink": "😉"
    "heart eyes": "😍"
    "kissing heart": "😘"
    "kissing closed eyes": "😚"
    "kissing": "😗"
    "kissing smiling eyes": "😙"
    "stuck out tongue winking eye": "😜"
    "stuck out tongue closed eyes": "😝"
    "stuck out tongue": "😛"
    "flushed": "😳"
    "grin": "😁"
    "pensive": "😔"
    "relieved": "😌"
    "unamused": "😒"
    "disappointed": "😞"
    "persevere": "😣"
    "cry": "😢"
    "joy": "😂"
    "sob": "😭"
    "sleepy": "😪"
    "disappointed relieved": "😥"
    "cold sweat": "😰"
    "sweat smile": "😅"
    "sweat": "😓"
    "weary": "😩"
    "tired face": "😫"
    "fearful": "😨"
    "scream": "😱"
    "angry": "😠"
    "rage": "😡"
    "triumph": "😤"
    "confounded": "😖"
    "laughing": "😆"
    "satisfied": "😆"
    "yum": "😋"
    "mask": "😷"
    "sunglasses": "😎"
    "sleeping": "😴"
    "dizzy face": "😵"
    "astonished": "😲"
    "worried": "😟"
    "frowning": "😦"
    "anguished": "😧"
    "smiling imp": "😈"
    "imp": "👿"
    "open mouth": "😮"
    "grimacing": "😬"
    "neutral face": "😐"
    "confused": "😕"
    "hushed": "😯"
    "no mouth": "😶"
    "innocent": "😇"
    "smirk": "😏"
    "expressionless": "😑"
    "man with gua pi mao": "👲"
    "man with turban": "👳"
    "cop": "👮"
    "construction worker": "👷"
    "guardsman": "💂"
    "baby": "👶"
    "boy": "👦"
    "girl": "👧"
    "man": "👨"
    "woman": "👩"
    "older man": "👴"
    "older woman": "👵"
    "person with blond hair": "👱"
    "angel": "👼"
    "princess": "👸"
    "smiley cat": "😺"
    "smile cat": "😸"
    "heart eyes cat": "😻"
    "kissing cat": "😽"
    "smirk cat": "😼"
    "scream cat": "🙀"
    "crying cat face": "😿"
    "joy cat": "😹"
    "pouting cat": "😾"
    "japanese ogre": "👹"
    "japanese goblin": "👺"
    "see no evil": "🙈"
    "hear no evil": "🙉"
    "speak no evil": "🙊"
    "skull": "💀"
    "alien": "👽"
    "hankey": "💩"
    "poop": "💩"
    "shit": "💩"
    "fire": "🔥"
    "sparkles": "✨"
    "star2": "🌟"
    "dizzy": "💫"
    "boom": "💥"
    "collision": "💥"
    "anger": "💢"
    "sweat drops": "💦"
    "droplet": "💧"
    "zzz": "💤"
    "dash": "💨"
    "ear": "👂"
    "eyes": "👀"
    "nose": "👃"
    "tongue": "👅"
    "lips": "👄"
    "+1": "👍"
    "thumbsup": "👍"
    "-1": "👎"
    "thumbsdown": "👎"
    "ok hand": "👌"
    "punch": "👊"
    "facepunch": "👊"
    "fist": "✊"
    "v": "✌️"
    "wave": "👋"
    "raised hand": "✋"
    "hand": "✋"
    "open hands": "👐"
    "point up 2": "👆"
    "point down": "👇"
    "point right": "👉"
    "point left": "👈"
    "raised hands": "🙌"
    "pray": "🙏"
    "point up": "☝️"
    "clap": "👏"
    "muscle": "💪"
    "walking": "🚶"
    "running": "🏃"
    "runner": "🏃"
    "dancer": "💃"
    "couple": "👫"
    "family": "👪"
    "two men holding hands": "👬"
    "two women holding hands": "👭"
    "couplekiss": "💏"
    "couple with heart": "💑"
    "dancers": "👯"
    "ok woman": "🙆"
    "no good": "🙅"
    "information desk person": "💁"
    "raising hand": "🙋"
    "massage": "💆"
    "haircut": "💇"
    "nail care": "💅"
    "bride with veil": "👰"
    "person with pouting face": "🙎"
    "person frowning": "🙍"
    "bow": "🙇"
    "tophat": "🎩"
    "crown": "👑"
    "womans hat": "👒"
    "athletic shoe": "👟"
    "mans shoe": "👞"
    "shoe": "👞"
    "sandal": "👡"
    "high heel": "👠"
    "boot": "👢"
    "shirt": "👕"
    "tshirt": "👕"
    "necktie": "👔"
    "womans clothes": "👚"
    "dress": "👗"
    "running shirt with sash": "🎽"
    "jeans": "👖"
    "kimono": "👘"
    "bikini": "👙"
    "briefcase": "💼"
    "handbag": "👜"
    "pouch": "👝"
    "purse": "👛"
    "eyeglasses": "👓"
    "ribbon": "🎀"
    "closed umbrella": "🌂"
    "lipstick": "💄"
    "yellow heart": "💛"
    "blue heart": "💙"
    "purple heart": "💜"
    "green heart": "💚"
    "heart": "❤️"
    "broken heart": "💔"
    "heartpulse": "💗"
    "heartbeat": "💓"
    "two hearts": "💕"
    "sparkling heart": "💖"
    "revolving hearts": "💞"
    "cupid": "💘"
    "love letter": "💌"
    "kiss": "💋"
    "ring": "💍"
    "gem": "💎"
    "bust in silhouette": "👤"
    "busts in silhouette": "👥"
    "speech balloon": "💬"
    "footprints": "👣"
    "thought balloon": "💭"
    "dog": "🐶"
    "wolf": "🐺"
    "cat": "🐱"
    "mouse": "🐭"
    "hamster": "🐹"
    "rabbit": "🐰"
    "frog": "🐸"
    "tiger": "🐯"
    "koala": "🐨"
    "bear": "🐻"
    "pig": "🐷"
    "pig nose": "🐽"
    "cow": "🐮"
    "boar": "🐗"
    "monkey face": "🐵"
    "monkey": "🐒"
    "horse": "🐴"
    "sheep": "🐑"
    "elephant": "🐘"
    "panda face": "🐼"
    "penguin": "🐧"
    "bird": "🐦"
    "baby chick": "🐤"
    "hatched chick": "🐥"
    "hatching chick": "🐣"
    "chicken": "🐔"
    "snake": "🐍"
    "turtle": "🐢"
    "bug": "🐛"
    "bee": "🐝"
    "honeybee": "🐝"
    "ant": "🐜"
    "beetle": "🐞"
    "snail": "🐌"
    "octopus": "🐙"
    "shell": "🐚"
    "tropical fish": "🐠"
    "fish": "🐟"
    "dolphin": "🐬"
    "flipper": "🐬"
    "whale": "🐳"
    "whale2": "🐋"
    "cow2": "🐄"
    "ram": "🐏"
    "rat": "🐀"
    "water buffalo": "🐃"
    "tiger2": "🐅"
    "rabbit2": "🐇"
    "dragon": "🐉"
    "racehorse": "🐎"
    "goat": "🐐"
    "rooster": "🐓"
    "dog2": "🐕"
    "pig2": "🐖"
    "mouse2": "🐁"
    "ox": "🐂"
    "dragon face": "🐲"
    "blowfish": "🐡"
    "crocodile": "🐊"
    "camel": "🐫"
    "dromedary camel": "🐪"
    "leopard": "🐆"
    "cat2": "🐈"
    "poodle": "🐩"
    "feet": "🐾"
    "paw prints": "🐾"
    "bouquet": "💐"
    "cherry blossom": "🌸"
    "tulip": "🌷"
    "four leaf clover": "🍀"
    "rose": "🌹"
    "sunflower": "🌻"
    "hibiscus": "🌺"
    "maple leaf": "🍁"
    "leaves": "🍃"
    "fallen leaf": "🍂"
    "herb": "🌿"
    "ear of rice": "🌾"
    "mushroom": "🍄"
    "cactus": "🌵"
    "palm tree": "🌴"
    "evergreen tree": "🌲"
    "deciduous tree": "🌳"
    "chestnut": "🌰"
    "seedling": "🌱"
    "blossom": "🌼"
    "globe with meridians": "🌐"
    "sun with face": "🌞"
    "full moon with face": "🌝"
    "new moon with face": "🌚"
    "new moon": "🌑"
    "waxing crescent moon": "🌒"
    "first quarter moon": "🌓"
    "moon": "🌔"
    "waxing gibbous moon": "🌔"
    "full moon": "🌕"
    "waning gibbous moon": "🌖"
    "last quarter moon": "🌗"
    "waning crescent moon": "🌘"
    "last quarter moon with face": "🌜"
    "first quarter moon with face": "🌛"
    "crescent moon": "🌙"
    "earth africa": "🌍"
    "earth americas": "🌎"
    "earth asia": "🌏"
    "volcano": "🌋"
    "milky way": "🌌"
    "stars": "🌠"
    "star": "⭐"
    "sunny": "☀️"
    "partly sunny": "⛅"
    "cloud": "☁️"
    "zap": "⚡"
    "umbrella": "☔"
    "snowflake": "❄️"
    "snowman": "⛄"
    "cyclone": "🌀"
    "foggy": "🌁"
    "rainbow": "🌈"
    "ocean": "🌊"
    "bamboo": "🎍"
    "gift heart": "💝"
    "dolls": "🎎"
    "school satchel": "🎒"
    "mortar board": "🎓"
    "flags": "🎏"
    "fireworks": "🎆"
    "sparkler": "🎇"
    "wind chime": "🎐"
    "rice scene": "🎑"
    "jack o lantern": "🎃"
    "ghost": "👻"
    "santa": "🎅"
    "christmas tree": "🎄"
    "gift": "🎁"
    "tanabata tree": "🎋"
    "tada": "🎉"
    "confetti ball": "🎊"
    "balloon": "🎈"
    "crossed flags": "🎌"
    "crystal ball": "🔮"
    "movie camera": "🎥"
    "camera": "📷"
    "video camera": "📹"
    "vhs": "📼"
    "cd": "💿"
    "dvd": "📀"
    "minidisc": "💽"
    "floppy disk": "💾"
    "computer": "💻"
    "iphone": "📱"
    "phone": "☎️"
    "telephone": "☎️"
    "telephone receiver": "📞"
    "pager": "📟"
    "fax": "📠"
    "satellite": "📡"
    "tv": "📺"
    "radio": "📻"
    "loud sound": "🔊"
    "sound": "🔉"
    "speaker": "🔈"
    "mute": "🔇"
    "bell": "🔔"
    "no bell": "🔕"
    "loudspeaker": "📢"
    "mega": "📣"
    "hourglass flowing sand": "⏳"
    "hourglass": "⌛"
    "alarm clock": "⏰"
    "watch": "⌚"
    "unlock": "🔓"
    "lock": "🔒"
    "lock with ink pen": "🔏"
    "closed lock with key": "🔐"
    "key": "🔑"
    "mag right": "🔎"
    "bulb": "💡"
    "flashlight": "🔦"
    "high brightness": "🔆"
    "low brightness": "🔅"
    "electric plug": "🔌"
    "battery": "🔋"
    "mag": "🔍"
    "bathtub": "🛁"
    "bath": "🛀"
    "shower": "🚿"
    "toilet": "🚽"
    "wrench": "🔧"
    "nut and bolt": "🔩"
    "hammer": "🔨"
    "door": "🚪"
    "smoking": "🚬"
    "bomb": "💣"
    "gun": "🔫"
    "hocho": "🔪"
    "knife": "🔪"
    "pill": "💊"
    "syringe": "💉"
    "moneybag": "💰"
    "yen": "💴"
    "dollar": "💵"
    "pound": "💷"
    "euro": "💶"
    "credit card": "💳"
    "money with wings": "💸"
    "calling": "📲"
    "e-mail": "📧"
    "inbox tray": "📥"
    "outbox tray": "📤"
    "email": "✉️"
    "envelope": "✉️"
    "envelope with arrow": "📩"
    "incoming envelope": "📨"
    "postal horn": "📯"
    "mailbox": "📫"
    "mailbox closed": "📪"
    "mailbox with mail": "📬"
    "mailbox with no mail": "📭"
    "postbox": "📮"
    "package": "📦"
    "memo": "📝"
    "pencil": "📝"
    "page facing up": "📄"
    "page with curl": "📃"
    "bookmark tabs": "📑"
    "bar chart": "📊"
    "chart with upwards trend": "📈"
    "chart with downwards trend": "📉"
    "scroll": "📜"
    "clipboard": "📋"
    "date": "📅"
    "calendar": "📆"
    "card index": "📇"
    "file folder": "📁"
    "open file folder": "📂"
    "scissors": "✂️"
    "pushpin": "📌"
    "paperclip": "📎"
    "black nib": "✒️"
    "pencil2": "✏️"
    "straight ruler": "📏"
    "triangular ruler": "📐"
    "closed book": "📕"
    "green book": "📗"
    "blue book": "📘"
    "orange book": "📙"
    "notebook": "📓"
    "notebook with decorative cover": "📔"
    "ledger": "📒"
    "books": "📚"
    "book": "📖"
    "open book": "📖"
    "bookmark": "🔖"
    "name badge": "📛"
    "microscope": "🔬"
    "telescope": "🔭"
    "newspaper": "📰"
    "art": "🎨"
    "clapper": "🎬"
    "microphone": "🎤"
    "headphones": "🎧"
    "musical score": "🎼"
    "musical note": "🎵"
    "notes": "🎶"
    "musical keyboard": "🎹"
    "violin": "🎻"
    "trumpet": "🎺"
    "saxophone": "🎷"
    "guitar": "🎸"
    "space invader": "👾"
    "video game": "🎮"
    "black joker": "🃏"
    "flower playing cards": "🎴"
    "mahjong": "🀄"
    "game die": "🎲"
    "dart": "🎯"
    "football": "🏈"
    "basketball": "🏀"
    "soccer": "⚽"
    "baseball": "⚾️"
    "tennis": "🎾"
    "8ball": "🎱"
    "rugby football": "🏉"
    "bowling": "🎳"
    "golf": "⛳"
    "mountain bicyclist": "🚵"
    "bicyclist": "🚴"
    "checkered flag": "🏁"
    "horse racing": "🏇"
    "trophy": "🏆"
    "ski": "🎿"
    "snowboarder": "🏂"
    "swimmer": "🏊"
    "surfer": "🏄"
    "fishing pole and fish": "🎣"
    "coffee": "☕"
    "tea": "🍵"
    "sake": "🍶"
    "baby bottle": "🍼"
    "beer": "🍺"
    "beers": "🍻"
    "cocktail": "🍸"
    "tropical drink": "🍹"
    "wine glass": "🍷"
    "fork and knife": "🍴"
    "pizza": "🍕"
    "hamburger": "🍔"
    "fries": "🍟"
    "poultry leg": "🍗"
    "meat on bone": "🍖"
    "spaghetti": "🍝"
    "curry": "🍛"
    "fried shrimp": "🍤"
    "bento": "🍱"
    "sushi": "🍣"
    "fish cake": "🍥"
    "rice ball": "🍙"
    "rice cracker": "🍘"
    "rice": "🍚"
    "ramen": "🍜"
    "stew": "🍲"
    "oden": "🍢"
    "dango": "🍡"
    "egg": "🍳"
    "bread": "🍞"
    "doughnut": "🍩"
    "custard": "🍮"
    "icecream": "🍦"
    "ice cream": "🍨"
    "shaved ice": "🍧"
    "birthday": "🎂"
    "cake": "🍰"
    "cookie": "🍪"
    "chocolate bar": "🍫"
    "candy": "🍬"
    "lollipop": "🍭"
    "honey pot": "🍯"
    "apple": "🍎"
    "green apple": "🍏"
    "tangerine": "🍊"
    "lemon": "🍋"
    "cherries": "🍒"
    "grapes": "🍇"
    "watermelon": "🍉"
    "strawberry": "🍓"
    "peach": "🍑"
    "melon": "🍈"
    "banana": "🍌"
    "pear": "🍐"
    "pineapple": "🍍"
    "sweet potato": "🍠"
    "eggplant": "🍆"
    "tomato": "🍅"
    "corn": "🌽"
    "house": "🏠"
    "house with garden": "🏡"
    "school": "🏫"
    "office": "🏢"
    "post office": "🏣"
    "hospital": "🏥"
    "bank": "🏦"
    "convenience store": "🏪"
    "love hotel": "🏩"
    "hotel": "🏨"
    "wedding": "💒"
    "church": "⛪"
    "department store": "🏬"
    "european post office": "🏤"
    "city sunrise": "🌇"
    "city sunset": "🌆"
    "japanese castle": "🏯"
    "european castle": "🏰"
    "tent": "⛺"
    "factory": "🏭"
    "tokyo tower": "🗼"
    "japan": "🗾"
    "mount fuji": "🗻"
    "sunrise over mountains": "🌄"
    "sunrise": "🌅"
    "night with stars": "🌃"
    "statue of liberty": "🗽"
    "bridge at night": "🌉"
    "carousel horse": "🎠"
    "ferris wheel": "🎡"
    "fountain": "⛲"
    "roller coaster": "🎢"
    "ship": "🚢"
    "boat": "⛵"
    "sailboat": "⛵"
    "speedboat": "🚤"
    "rowboat": "🚣"
    "anchor": "⚓"
    "rocket": "🚀"
    "airplane": "✈️"
    "seat": "💺"
    "helicopter": "🚁"
    "steam locomotive": "🚂"
    "tram": "🚊"
    "station": "🚉"
    "mountain railway": "🚞"
    "train2": "🚆"
    "bullettrain side": "🚄"
    "bullettrain front": "🚅"
    "light rail": "🚈"
    "metro": "🚇"
    "monorail": "🚝"
    "train": "🚋"
    "railway car": "🚃"
    "trolleybus": "🚎"
    "bus": "🚌"
    "oncoming bus": "🚍"
    "blue car": "🚙"
    "oncoming automobile": "🚘"
    "car": "🚗"
    "red car": "🚗"
    "taxi": "🚕"
    "oncoming taxi": "🚖"
    "articulated lorry": "🚛"
    "truck": "🚚"
    "rotating light": "🚨"
    "police car": "🚓"
    "oncoming police car": "🚔"
    "fire engine": "🚒"
    "ambulance": "🚑"
    "minibus": "🚐"
    "bike": "🚲"
    "aerial tramway": "🚡"
    "suspension railway": "🚟"
    "mountain cableway": "🚠"
    "tractor": "🚜"
    "barber": "💈"
    "busstop": "🚏"
    "ticket": "🎫"
    "vertical traffic light": "🚦"
    "traffic light": "🚥"
    "warning": "⚠️"
    "construction": "🚧"
    "beginner": "🔰"
    "fuelpump": "⛽"
    "izakaya lantern": "🏮"
    "lantern": "🏮"
    "slot machine": "🎰"
    "hotsprings": "♨️"
    "moyai": "🗿"
    "circus tent": "🎪"
    "performing arts": "🎭"
    "round pushpin": "📍"
    "triangular flag on post": "🚩"
    "jp": "🇯🇵"
    "kr": "🇰🇷"
    "de": "🇩🇪"
    "cn": "🇨🇳"
    "us": "🇺🇸"
    "fr": "🇫🇷"
    "es": "🇪🇸"
    "it": "🇮🇹"
    "ru": "🇷🇺"
    "gb": "🇬🇧"
    "uk": "🇬🇧"
    "one": "1️⃣"
    "two": "2️⃣"
    "three": "3️⃣"
    "four": "4️⃣"
    "five": "5️⃣"
    "six": "6️⃣"
    "seven": "7️⃣"
    "eight": "8️⃣"
    "nine": "9️⃣"
    "zero": "0️⃣"
    "keycap ten": "🔟"
    "1234": "🔢"
    "hash": "#️⃣"
    "symbols": "🔣"
    "arrow up": "⬆️"
    "arrow down": "⬇️"
    "arrow left": "⬅️"
    "arrow right": "➡️"
    "capital abcd": "🔠"
    "abcd": "🔡"
    "abc": "🔤"
    "arrow upper right": "↗️"
    "arrow upper left": "↖️"
    "arrow lower right": "↘️"
    "arrow lower left": "↙️"
    "left right arrow": "↔️"
    "arrow up down": "↕️"
    "arrows counterclockwise": "🔄"
    "arrow backward": "◀️"
    "arrow forward": "▶️"
    "arrow up small": "🔼"
    "arrow down small": "🔽"
    "leftwards arrow with hook": "↩️"
    "arrow right hook": "↪️"
    "information source": "ℹ️"
    "rewind": "⏪"
    "fast forward": "⏩"
    "arrow double up": "⏫"
    "arrow double down": "⏬"
    "arrow heading down": "⤵️"
    "arrow heading up": "⤴️"
    "ok": "🆗"
    "twisted rightwards arrows": "🔀"
    "repeat": "🔁"
    "repeat one": "🔂"
    "new": "🆕"
    "up": "🆙"
    "cool": "🆒"
    "free": "🆓"
    "ng": "🆖"
    "signal strength": "📶"
    "cinema": "🎦"
    "koko": "🈁"
    "u6307": "🈯"
    "u7a7a": "🈳"
    "u6e80": "🈵"
    "u5408": "🈴"
    "u7981": "🈲"
    "ideograph advantage": "🉐"
    "u5272": "🈹"
    "u55b6": "🈺"
    "u6709": "🈶"
    "u7121": "🈚"
    "restroom": "🚻"
    "mens": "🚹"
    "womens": "🚺"
    "baby symbol": "🚼"
    "wc": "🚾"
    "potable water": "🚰"
    "put litter in its place": "🚮"
    "parking": "🅿️"
    "wheelchair": "♿"
    "no smoking": "🚭"
    "u6708": "🈷️"
    "u7533": "🈸"
    "sa": "🈂️"
    "m": "Ⓜ️"
    "passport control": "🛂"
    "baggage claim": "🛄"
    "left luggage": "🛅"
    "customs": "🛃"
    "accept": "🉑"
    "secret": "㊙️"
    "congratulations": "㊗️"
    "cl": "🆑"
    "sos": "🆘"
    "id": "🆔"
    "no entry sign": "🚫"
    "underage": "🔞"
    "no mobile phones": "📵"
    "do not litter": "🚯"
    "non-potable water": "🚱"
    "no bicycles": "🚳"
    "no pedestrians": "🚷"
    "children crossing": "🚸"
    "no entry": "⛔"
    "eight spoked asterisk": "✳️"
    "sparkle": "❇️"
    "negative squared cross mark": "❎"
    "white check mark": "✅"
    "eight pointed black star": "✴️"
    "heart decoration": "💟"
    "vs": "🆚"
    "vibration mode": "📳"
    "mobile phone off": "📴"
    "a": "🅰️"
    "b": "🅱️"
    "ab": "🆎"
    "o2": "🅾️"
    "diamond shape with a dot inside": "💠"
    "loop": "➿"
    "recycle": "♻️"
    "aries": "♈"
    "taurus": "♉"
    "gemini": "♊"
    "cancer": "♋"
    "leo": "♌"
    "virgo": "♍"
    "libra": "♎"
    "scorpius": "♏"
    "sagittarius": "♐"
    "capricorn": "♑"
    "aquarius": "♒"
    "pisces": "♓"
    "ophiuchus": "⛎"
    "six pointed star": "🔯"
    "atm": "🏧"
    "chart": "💹"
    "heavy dollar sign": "💲"
    "currency exchange": "💱"
    "copyright": "©️"
    "registered": "®️"
    "tm": "™️"
    "x": "❌"
    "bangbang": "‼️"
    "interrobang": "⁉️"
    "heavy exclamation mark": "❗"
    "exclamation": "❗"
    "question": "❓"
    "grey exclamation": "❕"
    "grey question": "❔"
    "o": "⭕"
    "top": "🔝"
    "end": "🔚"
    "back": "🔙"
    "on": "🔛"
    "soon": "🔜"
    "arrows clockwise": "🔃"
    "clock12": "🕛"
    "clock1230": "🕧"
    "clock1": "🕐"
    "clock130": "🕜"
    "clock2": "🕑"
    "clock230": "🕝"
    "clock3": "🕒"
    "clock330": "🕞"
    "clock4": "🕓"
    "clock430": "🕟"
    "clock5": "🕔"
    "clock530": "🕠"
    "clock6": "🕕"
    "clock7": "🕖"
    "clock8": "🕗"
    "clock9": "🕘"
    "clock10": "🕙"
    "clock11": "🕚"
    "clock630": "🕡"
    "clock730": "🕢"
    "clock830": "🕣"
    "clock930": "🕤"
    "clock1030": "🕥"
    "clock1130": "🕦"
    "heavy multiplication x": "✖️"
    "heavy plus sign": "➕"
    "heavy minus sign": "➖"
    "heavy division sign": "➗"
    "spades": "♠️"
    "hearts": "♥️"
    "clubs": "♣️"
    "diamonds": "♦️"
    "white flower": "💮"
    "100": "💯"
    "heavy check mark": "✔️"
    "ballot box with check": "☑️"
    "radio button": "🔘"
    "link": "🔗"
    "curly loop": "➰"
    "wavy dash": "〰️"
    "part alternation mark": "〽️"
    "trident": "🔱"
    "black medium square": "◼️"
    "white medium square": "◻️"
    "black medium small square": "◾"
    "white medium small square": "◽"
    "black small square": "▪️"
    "white small square": "▫️"
    "small red triangle": "🔺"
    "black square button": "🔲"
    "white square button": "🔳"
    "black circle": "⚫"
    "white circle": "⚪"
    "red circle": "🔴"
    "large blue circle": "🔵"
    "small red triangle down": "🔻"
    "white large square": "⬜"
    "black large square": "⬛"
    "large orange diamond": "🔶"
    "large blue diamond": "🔷"
    "small orange diamond": "🔸"
    "small blue diamond": "🔹"
