exports.keyCodes =
  "a"                    : 0x00
  "b"                    : 0x0B
  "c"                    : 0x08
  "d"                    : 0x02
  "e"                    : 0x0E
  "f"                    : 0x03
  "g"                    : 0x05
  "h"                    : 0x04
  "i"                    : 0x22
  "j"                    : 0x26
  "k"                    : 0x28
  "l"                    : 0x25
  "m"                    : 0x2E
  "n"                    : 0x2D
  "o"                    : 0x1F
  "p"                    : 0x23
  "q"                    : 0x0C
  "r"                    : 0x0F
  "s"                    : 0x01
  "t"                    : 0x11
  "u"                    : 0x20
  "v"                    : 0x09
  "w"                    : 0x0D
  "x"                    : 0x07
  "y"                    : 0x10
  "z"                    : 0x06
  "grave"                : 0x32
  "keypaddecimal"        : 0x41
  "keypadmultiply"       : 0x43
  "keypadplus"           : 0x45
  "keypadclear"          : 0x47
  "keypaddivide"         : 0x4B
  "keypadenter"          : 0x4C
  "keypadminus"          : 0x4E
  "keypadequals"         : 0x51
  "keypad0"              : 0x52
  "keypad1"              : 0x53
  "keypad2"              : 0x54
  "keypad3"              : 0x55
  "keypad4"              : 0x56
  "keypad5"              : 0x57
  "keypad6"              : 0x58
  "keypad7"              : 0x59
  "keypad8"              : 0x5B
  "keypad9"              : 0x5C
  "return"               : 0x24
  "\n"                   : 0x24
  "tab"                  : 0x30
  "\t"                   : 0x30
  "space"                : 0x31
  " "                    : 0x31
  "delete"               : 0x33
  "escape"               : 0x35
  "command"              : 0x37
  "shift"                : 0x38
  "capslock"             : 0x39
  "option"               : 0x3A
  "control"              : 0x3B
  "rightshift"           : 0x3C
  "rightoption"          : 0x3D
  "rightcontrol"         : 0x3E
  "function"             : 0x3F
  "f17"                  : 0x40
  "volumeup"             : 0x48
  "volumedown"           : 0x49
  "mute"                 : 0x4A
  "f18"                  : 0x4F
  "f19"                  : 0x50
  "f20"                  : 0x5A
  "f5"                   : 0x60
  "f6"                   : 0x61
  "f7"                   : 0x62
  "f3"                   : 0x63
  "f8"                   : 0x64
  "f9"                   : 0x65
  "f11"                  : 0x67
  "f13"                  : 0x69
  "f16"                  : 0x6A
  "f14"                  : 0x6B
  "f10"                  : 0x6D
  "f12"                  : 0x6F
  "f15"                  : 0x71
  "help"                 : 0x72
  "home"                 : 0x73
  "pageup"               : 0x74
  "forwarddelete"        : 0x75
  "f4"                   : 0x76
  "end"                  : 0x77
  "f2"                   : 0x78
  "pagedown"             : 0x79
  "f1"                   : 0x7A
  "left"                 : 0x7B
  "right"                : 0x7C
  "down"                 : 0x7D
  "up"                   : 0x7E
  "backspace"            : 0x33
  "enter"                : 0x24
  "1"                    : 0x12
  "2"                    : 0x13
  "3"                    : 0x14
  "4"                    : 0x15
  "5"                    : 0x17
  "6"                    : 0x16
  "7"                    : 0x1A
  "8"                    : 0x1C
  "9"                    : 0x19
  "0"                    : 0x1D
  "="                    : 0x18
  "-"                    : 0x1B
  "]"                    : 0x1E
  "["                    : 0x21
  "'"                    : 0x27
  ";"                    : 0x29
  "\\"                   : 0x2A
  ","                    : 0x2B
  "/"                    : 0x2C
  "."                    : 0x2F
  "`"                    : 0x32

exports.keyCodesRegular =
  "grave"                : 0x32
  "keypaddecimal"        : 0x41
  "keypadmultiply"       : 0x43
  "keypadplus"           : 0x45
  "keypadclear"          : 0x47
  "keypaddivide"         : 0x4B
  "keypadenter"          : 0x4C
  "keypadminus"          : 0x4E
  "keypadequals"         : 0x51
  "keypad0"              : 0x52
  "keypad1"              : 0x53
  "keypad2"              : 0x54
  "keypad3"              : 0x55
  "keypad4"              : 0x56
  "keypad5"              : 0x57
  "keypad6"              : 0x58
  "keypad7"              : 0x59
  "keypad8"              : 0x5B
  "keypad9"              : 0x5C
  "return"               : 0x24
  "\n"                   : 0x24
  "tab"                  : 0x30
  "\t"                   : 0x30
  "space"                : 0x31
  " "                    : 0x31
  "delete"               : 0x33
  "escape"               : 0x35
  "command"              : 0x37
  "shift"                : 0x38
  "capslock"             : 0x39
  "option"               : 0x3A
  "control"              : 0x3B
  "rightshift"           : 0x3C
  "rightoption"          : 0x3D
  "rightcontrol"         : 0x3E
  "function"             : 0x3F
  "f17"                  : 0x40
  "volumeup"             : 0x48
  "volumedown"           : 0x49
  "mute"                 : 0x4A
  "f18"                  : 0x4F
  "f19"                  : 0x50
  "f20"                  : 0x5A
  "f5"                   : 0x60
  "f6"                   : 0x61
  "f7"                   : 0x62
  "f3"                   : 0x63
  "f8"                   : 0x64
  "f9"                   : 0x65
  "f11"                  : 0x67
  "f13"                  : 0x69
  "f16"                  : 0x6A
  "f14"                  : 0x6B
  "f10"                  : 0x6D
  "f12"                  : 0x6F
  "f15"                  : 0x71
  "help"                 : 0x72
  "home"                 : 0x73
  "pageup"               : 0x74
  "forwarddelete"        : 0x75
  "f4"                   : 0x76
  "end"                  : 0x77
  "f2"                   : 0x78
  "pagedown"             : 0x79
  "f1"                   : 0x7A
  "left"                 : 0x7B
  "right"                : 0x7C
  "down"                 : 0x7D
  "up"                   : 0x7E
  "backspace"            : 0x33
  "enter"                : 0x24
  "a"                    : 0x00
  "s"                    : 0x01
  "d"                    : 0x02
  "f"                    : 0x03
  "h"                    : 0x04
  "g"                    : 0x05
  "z"                    : 0x06
  "x"                    : 0x07
  "c"                    : 0x08
  "v"                    : 0x09
  "b"                    : 0x0B
  "q"                    : 0x0C
  "w"                    : 0x0D
  "e"                    : 0x0E
  "r"                    : 0x0F
  "y"                    : 0x10
  "t"                    : 0x11
  "1"                    : 0x12
  "2"                    : 0x13
  "3"                    : 0x14
  "4"                    : 0x15
  "5"                    : 0x17
  "6"                    : 0x16
  "="                    : 0x18
  "9"                    : 0x19
  "7"                    : 0x1A
  "-"                    : 0x1B
  "8"                    : 0x1C
  "0"                    : 0x1D
  "]"                    : 0x1E
  "o"                    : 0x1F
  "u"                    : 0x20
  "["                    : 0x21
  "i"                    : 0x22
  "p"                    : 0x23
  "l"                    : 0x25
  "j"                    : 0x26
  "k"                    : 0x28
  "'"                    : 0x27
  ";"                    : 0x29
  "\\"                   : 0x2A
  ","                    : 0x2B
  "/"                    : 0x2C
  "n"                    : 0x2D
  "m"                    : 0x2E
  "."                    : 0x2F
  "`"                    : 0x32

exports.keyCodesShift =
  "A"                    : 0x00
  "B"                    : 0x0B
  "C"                    : 0x08
  "D"                    : 0x02
  "E"                    : 0x0E
  "F"                    : 0x03
  "G"                    : 0x05
  "H"                    : 0x04
  "I"                    : 0x22
  "J"                    : 0x26
  "K"                    : 0x28
  "L"                    : 0x25
  "M"                    : 0x2E
  "N"                    : 0x2D
  "O"                    : 0x1F
  "P"                    : 0x23
  "Q"                    : 0x0C
  "R"                    : 0x0F
  "S"                    : 0x01
  "T"                    : 0x11
  "U"                    : 0x20
  "V"                    : 0x09
  "W"                    : 0x0D
  "X"                    : 0x07
  "Y"                    : 0x10
  "Z"                    : 0x06
  "<"                    : 0x2B
  ">"                    : 0x2F
  "{"                    : 0x21
  "}"                    : 0x1E
  ")"                    : 0x1D
  "("                    : 0x19
  "!"                    : 0x12
  "|"                    : 0x2A
  ":"                    : 0x29
  "&"                    : 0x1A
  "%"                    : 0x17
  "?"                    : 0x2C
  "*"                    : 0x1C
  "~"                    : 0x32
  "@"                    : 0x13
  "$"                    : 0x15
  "^"                    : 0x16
  "+"                    : 0x18
  "#"                    : 0x14
  "_"                    : 0x1B
  "#"                    : 0x14
  "\""                   : 0x27
