@CommandoSettings = 
  defaultBrowser: "Chrome"
  websites:
    amazon: "amazon.com"
    "amazon console": "console.aws.amazon.com"
    atmosphere: "atmospherejs.com"
    balsamic: "www.mybalsamiq.com/login"
    cloudflare: "www.cloudflare.com"
    craigslist: "craigslist.com"
    github: "github.com"
    gmail: "mail.google.com"
    "google docs": "docs.google.com"
    heroku: "heroku.com"
    modulus: "modulus.io/user/dashboard"
    "mongo hq": "app.mongohq.com/databases"
  applications:
    term: "iTerm"
    web: "Chrome"
    chrome: "Chrome"
    sky: "Skype"
    billy: "Adobe Illustrator"
    shop: "Adobe Photoshop CC 2014"
    calendar: "Calendar"
    drag: "Dragon Dictate"
    find: "Path Finder"
    logic: "Logic Pro X"
    mail: "Mail"
    message: "Messages"
    pass: "1Password"
    page: "Pages"
    robo: "Robomongo"
    system: "System Preferences"
    tree: "SourceTree"
    tune: "iTunes"
    preview: "Preview"
    sublime: "Sublime Text"
    activity: "Activity Monitor"
    safari: "Safari"
    xcode: "Xcode"
    automate: "Automator"
  abbreviations:
    standing: "stdin"
    standout: "stdout"
    administrator: "admin"
    administrators: "admins"
    alternate: "alt"
    application: "app"
    applications: "apps"
    argument: "arg"
    arguments: "args"
    attribute: "attr"
    attributes: "attrs"
    author: "auth"
    binary: "bin"
    button: "btn"
    column: "col"
    command: "cmd"
    define: "def"
    descending: "desc"
    develop: "dev"
    directory: "dir"
    divider: "div"
    document: "doc"
    execute: "exec"
    favorite: "fav"
    function: "func"
    image: "img"
    initialize: "init"
    integer: "int"
    iterate: "iter"
    jason: "json"
    large: "lg"
    length: "len"
    library: "lib"
    medium: "md"
    number: "num"
    object: "obj"
    parameter: "param"
    parameters: "params"
    position: "pos"
    previous: "prev"
    pseudo: "sudo"
    reference: "ref"
    references: "refs"
    request: "req"
    result: "res"
    revision: "rev"
    source: "src"
    standard: "std"
    string: "str"
    system: "sys"
    temporary: "tmp"
    text: "txt"
    utilities: "utils"
    utility: "util"
    value: "val"
    variable: "var"
    increment: "inc"
    "inc.": "inc"
    # multi word abbreviations
    "stripe test card": "4242424242424242"
  codeSnippets:
    "if else": "ife"
    if: "if"
    switch: "swi"
    for: "for"
    log: "log"
    else: "el"
    "else if": "elif"
    require: "req"
    ternary: "ter"
    "try catch": "try"
    unless: "unl"
    class: "cla"
    define: "def"
    "define initializer": "defi"
    "define self": "defs"
    "while": "while"
    "each": "ea"
    "each pair": "eap"
    "each with index": "eawi"
    "find all": "fina"
  # this can be changed. 48 = TAB, 36 = ENTER, etc
  codeSnippetCompletionKeystroke: "key code 48"

    
            

    
      
    


