@CommandoSettings = 
  defaultBrowser: "Chrome"
  modules:
    global: true
    smartnav: false
    css: false
    javascript: false
    ruby: false
    shell: false
  websites:
    amazon: "http://www.amazon.com"
    "amazon console": "https://console.aws.amazon.com"
    craigslist: "craigslist.com"
    github: "github.com"
    gmail: "mail.google.com"
    "google docs": "docs.google.com"
  applications:
    term: "iTerm"
    web: "Chrome"
    chrome: "Chrome"
    sky: "Skype"
    billy: "Adobe Illustrator"
    shop: "Adobe Photoshop CC 2014"
    calendar: "Calendar"
    drag: "Dragon Dictate"
    find: "Path Finder"
    logic: "Logic Pro X"
    mail: "Mail"
    message: "Messages"
    pass: "1Password"
    page: "Pages"
    robo: "Robomongo"
    system: "System Preferences"
    tree: "SourceTree"
    tune: "iTunes"
    preview: "Preview"
    sublime: "Sublime Text"
    activity: "Activity Monitor"
    safari: "Safari"
    xcode: "Xcode"
    automate: "Automator"
    store: "App Store"
    quicktime: "QuickTime Player"
    parallels: "Parallels Desktop"
  abbreviations:
    standing: "stdin"
    standout: "stdout"
    administrator: "admin"
    administrators: "admins"
    alternate: "alt"
    apartment: "apt"
    application: "app"
    applications: "apps"
    architecture: "arch"
    argument: "arg"
    arguments: "args"
    attribute: "attr"
    attributes: "attrs"
    allocate: "alloc"
    authenticate: "auth"
    authentic: "auth"
    author: "auth"
    binary: "bin"
    button: "btn"
    calculate: "calc"
    call: "col"
    column: "col"
    command: "cmd"
    define: "def"
    descending: "desc"
    develop: "dev"
    directory: "dir"
    divider: "div"
    document: "doc"
    execute: "exec"
    favorite: "fav"
    function: "func"
    image: "img"
    initialize: "init"
    integer: "int"
    iterate: "iter"
    jason: "json"
    large: "lg"
    length: "len"
    library: "lib"
    medium: "md"
    minimum: "min"
    number: "num"
    navigate: "nav"
    navigation: "nav"
    object: "obj"
    parameter: "param"
    parameters: "params"
    position: "pos"
    previous: "prev"
    pseudo: "sudo"
    reference: "ref"
    references: "refs"
    request: "req"
    result: "res"
    revision: "rev"
    source: "src"
    standard: "std"
    string: "str"
    system: "sys"
    temporary: "tmp"
    text: "txt"
    utilities: "utils"
    utility: "util"
    value: "val"
    variable: "var"
    increment: "inc"
    "inc.": "inc"
    # multi word abbreviations
    "stripe test card": "4242424242424242"
  codeSnippets:
    "if else": "ife"
    if: "if"
    switch: "swi"
    for: "for"
    log: "log"
    else: "el"
    "else if": "elif"
    require: "req"
    ternary: "ter"
    "try catch": "try"
    unless: "unl"
    class: "cla"
    define: "def"
    "define initializer": "defi"
    "define self": "defs"
    "while": "while"
    "each": "ea"
    "each pair": "eap"
    "each with index": "eawi"
    "find all": "fina"
  # this can be changed. Tab, Return, Escape, etc
  codeSnippetCompletionKey: "Tab"
  directories:
    home: "~"
    applications: "/Applications"
    users: "/Users"
    desktop: "~/Desktop"
    documents: "~/Documents"
    music: "~/Music"
    downloads: "~/Downloads"
  passwords:
    example: "password"
  emails:
    example: "email@example.com"
  usernames:
    example: "username1"
  translations:
    "january": "January"
    "february": "February"
    "i'm": "I'm"
    "isobject": "object"
    "maine": "main"
    "o'clock": ":00"
  contexts:
    global: "global"
    emacs: "emacs"
    mate: "textmate"
  dragonContexts: [
    "Global"
    "iTerm"
  ]
  workflows:
    "workflow test": "yellsnik it worked clamor"
  shellCommands:
    permissions: "chmod "
    access: "chmod "
    cat: "cat "
    copy: "cp "
    move: "mv "
    remove: "rm "
    "remove directory": "rmdir "
    "make directory": "mkdir "
    link: "ln "
    man: "man "
  menuItemAliases:
    review: "view"
  systemPreferences:
    universal: "com.apple.preference.universalaccess"
    "app store": "com.apple.preferences.appstore"
    bluetooth: "com.apple.preferences.Bluetooth"
    "date time": "com.apple.preference.datetime"
    desktop: "com.apple.preference.desktopscreeneffect"
    speech: "com.apple.preference.speech"
    display: "com.apple.preference.displays"
    dock: "com.apple.preference.dock"
    energy: "com.apple.preference.energysaver"
    extensions: "com.apple.preferences.extensions"
    general: "com.apple.preference.general"
    icloud: "com.apple.preferences.icloud"
    "internet accounts": "com.apple.preferences.internetaccounts"
    keyboard: "com.apple.preference.keyboard"
    localization: "com.apple.Localization"
    expose: "com.apple.preference.expose"
    mouse: "com.apple.preference.mouse"
    network: "com.apple.preference.network"
    notifications: "com.apple.preference.notifications"
    "parental controls": "com.apple.preferences.parentalcontrols"
    print: "com.apple.preference.printfax"
    security: "com.apple.preference.security"
    sharing: "com.apple.preferences.sharing"
    sound: "com.apple.preference.sound"
    spotlight: "com.apple.preference.spotlight"
    "startup disk": "com.apple.preference.startupdisk"
    backup: "com.apple.prefs.backup"
    trackpad: "com.apple.preference.trackpad"
    users: "com.apple.preferences.users"
    
            

    
      
    


