w = (commaSeparatedString) ->
  commaSeparatedString.split(/, |\n/)

@Homonyms =
  initialize: ->
    Homonyms.sorted = {}
    s = Homonyms.sorted
    for row in Homonyms.values
      for word in row
        s[word.toLowerCase()] = row
  next: (word) ->
    list = Homonyms.sorted[word]
    if list?
      index = _.map(list, (e) -> e.toLowerCase()).indexOf(word) + 1
      if index >= list.length
        index = 0
      list[index]
  values: [
    w "acclamation, acclimation"
    w "acts, ax"
    w "ad, add"
    w "ade, aid, aide"
    w "ades, aids, aides"
    w "adherence, adherents"
    w "adieu, ado"
    w "admittance, admittants"
    w "adolescence, adolescents"
    w "ads, adds, adz"
    w "aerie, airy"
    w "aero, arrow"
    w "agar, auger, augur"
    w "agars, augers, augurs"
    w "ail, ale"
    w "ails, ales"
    w "air, ere, heir"
    w "airs, heirs"
    w "aisle, I'll, isle"
    w "all, awl"
    w "allowed, aloud"
    w "all's, awls"
    w "altar, alter"
    w "altars, alters"
    w "analyst, annalist"
    w "analysts, annalists"
    w "ant, aunt"
    w "ants, aunts"
    w "ante, anti, aunty"
    w "apatite, appetite"
    w "append, upend"
    w "appended, upended"
    w "appending, upending"
    w "arc, ark"
    w "arcs, arks"
    w "arrant, errant"
    w "ascent, assent"
    w "ascents, assents"
    w "assistance, assistants"
    w "ate, eight"
    w "attendance, attendants"
    w "aught, ought"
    w "auks, ox"
    w "aural, oral"
    w "aureole, oriole"
    w "aureoles, orioles"
    w "auricle, oracle"
    w "auricles, oracles"
    w "auxin, oxen"
    w "away, aweigh"
    w "awed, odd"
    w "awes, os"
    w "awful, offal"
    w "awn, on"
    w "axel, axil, axle"
    w "axes, axis"
    w "aye , eye, i"
    w "ayes, eyes"
    w "baa, bah"
    w "bad, bade"
    w "baal, bail, bale"
    w "bailer, baler"
    w "bailers, balers"
    w "bailing, baling"
    w "bails, bales"
    w "bait, bate"
    w "baited, bated"
    w "baits, bates"
    w "baize, bays"
    w "bald, balled, bawled"
    w "balks, box"
    w "ball, bawl"
    w "balls, bawls"
    w "balm, bomb"
    w "balms, bombs"
    w "baloney, bologna"
    w "band, banned"
    w "bans, banns, bands"
    w "bar, barre"
    w "bard, barred"
    w "bare, bear"
    w "bares, bears"
    w "baring, bearing"
    w "baron, barren"
    w "barrel, beryl"
    w "base, bass"
    w "based, baste"
    w "basis, basses"
    w "bask, basque"
    w "basks, basques"
    w "bate, bait"
    w "bated, baited"
    w "bates, baits"
    w "bauble, bobble"
    w "baubles, bobbles"
    w "baud, bawd"
    w "bawdy, body"
    w "bay, bey"
    w "bazaar, bizarre"
    w "be, bee"
    w "beach, beech"
    w "beaches, beeches"
    w "beat, beet"
    w "beats, beets"
    w "beau, bow"
    w "beaus, bows"
    w "been, bin"
    w "beer, bier"
    w "beers, biers"
    w "beetle, betel"
    w "bees, bise"
    w "belligerence, belligerents"
    w "bell, belle"
    w "bells, belles"
    w "berg, burg"
    w "bergs, burgs"
    w "berries, buries"
    w "berry, bury"
    w "berth, birth"
    w "berthed, birthed"
    w "berthing, birthing"
    w "berths, births"
    w "better, bettor"
    w "bib, bibb"
    w "bibs, bibbs"
    w "bight, bite, byte"
    w "bights, bites, bytes"
    w "billed, build"
    w "bird, burred"
    w "birr, burr"
    w "bit, bitt"
    w "bits, bitts"
    w "blend, blende"
    w "blends, blendes"
    w "blew, blue"
    w "bloc, block"
    w "blocs, blocks"
    w "blond, blonde"
    w "boar, bore"
    w "board, bored"
    w "boarder, border"
    w "boarders, borders"
    w "boars, bores"
    w "bode, bowed"
    w "bodies, body's"
    w "bogie, bogey, bogy"
    w "bold, bowled"
    w "bolder, boulder"
    w "bole, boll, bowl"
    w "boles, bolls, bowls"
    w "boos, booze"
    w "bootie, booty"
    w "born, bourn"
    w "borough, burro, burrow"
    w "boroughs, burros, burrows"
    w "bouillon, bullion"
    w "bow, bough"
    w "bows, boughs"
    w "brae, bray"
    w "braid, brayed"
    w "braille, brale"
    w "braise, brays, braze"
    w "brake, break"
    w "brakes, breaks"
    w "braking, breaking"
    w "breach, breech"
    w "breaches, breeches"
    w "bread, bred"
    w "brede, breed,"
    w "bredes, breeds"
    w "brewed, brood"
    w "brews, bruise"
    w "bridal, bridle"
    w "broach, brooch"
    w "broom, brougham"
    w "brooms, broughams"
    w "browse, brows"
    w "bruit, brute"
    w "buccal, buckle"
    w "burger, burgher"
    w "burgers, burghers"
    w "bus , buss"
    w "buses, busses"
    w "bussed, bust"
    w "but, butt"
    w "buts, butts"
    w "buy, by, bye"
    w "buyer, byer"
    w "buyers, byers"
    w "buys, byes"
    w "cache, cash"
    w "cached, cashed"
    w "caches, cashes"
    w "caching, cashing"
    w "cachou , cashew"
    w "cachous, cashews"
    w "calendar, calender"
    w "calendars, calenders"
    w "calix, calyx"
    w "calixes, calyxes"
    w "calk, caulk"
    w "calks, caulks"
    w "call, caul"
    w "caller, choler, collar"
    w "callers, collars"
    w "cannon, canon"
    w "cannons, canons"
    w "cant, can't"
    w "canter, cantor"
    w "canters, cantors"
    w "canvas, canvass"
    w "canvases, canvasses"
    w "capital, capitol"
    w "capitals, capitols"
    w "caret, carrot, karat"
    w "carets, carrots, karats"
    w "caries, carries"
    w "carol, carrel"
    w "carols, carrels"
    w "cart, kart"
    w "carts, karts"
    w "cask, casque"
    w "casks, casques"
    w "cast, caste"
    w "caster, castor"
    w "casters, castors"
    w "casts, castes"
    w "catch, ketch"
    w "catches, ketches"
    w "cat'll, cattle"
    w "caudal, caudle, coddle"
    w "cause, caws"
    w "cawed, cod"
    w "cedar, seeder"
    w "cedars, seeders"
    w "cede, seed"
    w "ceded, seeded"
    w "cedes, seeds"
    w "ceding, seeding"
    w "ceil, seal, seel"
    w "ceils, seals, seels"
    w "ceiling, sealing"
    w "ceilings, sealings"
    w "cell, sell"
    w "cellar, seller"
    w "cellars, sellers"
    w "cellar's, seller's"
    w "cells, sells"
    w "cense, cents, scents, sense"
    w "censers, censors, sensors"
    w "census, senses"
    w "cent, scent, sent"
    w "cents, sense"
    w "centuries, century's"
    w "cere, sear, seer, sere"
    w "ceres, sears, seers, seres"
    w "cereal, serial"
    w "cereals, serials"
    w "cession, session"
    w "cessions, sessions"
    w "chalk, chock"
    w "chalks, chocks"
    w "chance, chants"
    w "chanty, shanty"
    w "chantys, shantys"
    w "chard, charred"
    w "chary, cherry"
    w "chased, chaste"
    w "cheap, cheep"
    w "check, cheque, czech"
    w "checks, cheques, czechs"
    w "chews, choose"
    w "chic, sheik"
    w "chili, chilly"
    w "chitin, chiton"
    w "choir, quire"
    w "choirs, quires"
    w "choral, coral"
    w "chorale, corral"
    w "chorales, corrals"
    w "chord, cord, cored"
    w "chordate, cordate"
    w "chords, cords"
    w "chott, shot"
    w "chotts, shots"
    w "chough, chuff"
    w "choughs, chuffs"
    w "chrism, chrisom"
    w "chucker, chukker"
    w "chuckers, chukkers"
    w "chute, shoot"
    w "chutes, shoots"
    w "cingular, singular"
    w "cirrus, serous"
    w "cist, cyst"
    w "cists, cysts"
    w "citable, sightable"
    w "cite, sight, site"
    w "cited, sighted, sited"
    w "cites, sights, sites"
    w "citing, sighting, siting"
    w "clack, claque"
    w "clacks, claques"
    w "claimant, clamant"
    w "claimants, clamants"
    w "clause, claws"
    w "clawed, clod"
    w "clew, clue"
    w "clews, clues"
    w "click, clique, klick"
    w "clicks, cliques, klicks"
    w "climb, clime"
    w "climbs, climes"
    w "close, clothes"
    w "coal, cole, kohl"
    w "coarse, corse, course"
    w "coat, cote"
    w "coats, cotes"
    w "coax, cokes"
    w "cocks, cox"
    w "coffer, cougher"
    w "coffers, coughers"
    w "coin, quoin"
    w "coins, quoins"
    w "collared, collard"
    w "colonel, kernel"
    w "colonels, colonel's, kernels"
    w "competence, competents"
    w "complacent, complaisant"
    w "complement, compliment"
    w "complementary, complimentary"
    w "complemented, complimented"
    w "complementing, complimenting"
    w "concord, conquered"
    w "confectionary, confectionery"
    w "conk, conch"
    w "conks, conchs"
    w "coo, coup"
    w "coop, coupe"
    w "coops, coupes"
    w "coos, coups"
    w "cops, copse"
    w "coquet, coquette"
    w "cord, cored"
    w "core, corps"
    w "correspondence, correspondents"
    w "cosign, cosine"
    w "cosigns, cosines"
    w "council, counsel"
    w "councils, counsels"
    w "councillor, counselor"
    w "councillors, counselors"
    w "cousin, cozen"
    w "cousins, cozens"
    w "coward, cowered, cowherd"
    w "craft, kraft"
    w "crape, crepe"
    w "crapes, crepes"
    w "crater, krater"
    w "craters, kraters"
    w "crawl, kraal"
    w "crawls, kraals"
    w "creak, creek"
    w "creaks, creeks"
    w "crewel, cruel"
    w "crews, cruise, cruse"
    w "crows, croze"
    w "crude, crewed"
    w "cue, queue"
    w "cues, queues"
    w "currant, current"
    w "currants, currents"
    w "curser, cursor"
    w "cursers, cursors"
    w "cygnet, signet"
    w "cygnets, signets"
    w "cymbal, symbol"
    w "cymbals, symbols"
    w "dam, damn"
    w "dammed, damned"
    w "damming, damning"
    w "dams, damns"
    w "dane , deign"
    w "danes, deigns"
    w "dawn, don"
    w "dawns, dons"
    w "days, daze"
    w "dean, dene"
    w "deans, dene"
    w "dear, deer"
    w "deem, deme"
    w "deems, demes"
    w "defuse, diffuse"
    w "delinquence, delinquents"
    w "dense, dents"
    w "descent, dissent"
    w "dental, dentil"
    w "dependence, dependents"
    w "depravation, deprivation"
    w "depravations, deprivations"
    w "descent, dissent"
    w "descents, dissents"
    w "deviance, deviants"
    w "devisor, divisor"
    w "devisors, divisors"
    w "dew, do, due"
    w "dewed, dude"
    w "dewing, doing"
    w "dews, dues"
    w "die, dye"
    w "died, dyed"
    w "dies, dyes"
    w "dine, dyne"
    w "dines, dynes"
    w "dire, dyer"
    w "disburse, disperse"
    w "disburses, disperses"
    w "discreet, discrete"
    w "discussed, disgust"
    w "dissidence, dissidents"
    w "djinn, gin"
    w "do doe, dough"
    w "doc, dock"
    w "docs, docks"
    w "doe, dough"
    w "doer, dour"
    w "does, doze, doughs"
    w "doing, dewing"
    w "done, dun"
    w "dos, dues"
    w "dost, dust"
    w "douse, dowse"
    w "droop, drupe"
    w "droops, drupes"
    w "dual, duel"
    w "duals, duels"
    w "ducked, duct"
    w "dyeing, dying"
    w "earn, erne, urn"
    w "earns, ernes, urns"
    w "eave, eve"
    w "eaves, eves"
    w "eek, eke"
    w "eeks, ekes"
    w "eerie, erie"
    w "elicit, illicit"
    w "elude, allude"
    w "eludes, alludes"
    w "emerge, immerge"
    w "emerged, immerged"
    w "emerges, immerges"
    w "emerging, immerging"
    w "encyst, insist"
    w "encysts, insists"
    w "enfold, infold"
    w "enfolds, infolds"
    w "ensure, insure"
    w "ensure, insuring"
    w "ensured, insured"
    w "ensuring, insures"
    w "epic, epoch"
    w "epics, epochs"
    w "equivalence, equivalents"
    w "erupt, irrupt"
    w "eruption, irruption"
    w "eruptions, irruptions"
    w "eruptive, irruptive"
    w "eruptively, irruptively"
    w "ewe, yew, you"
    w "ewer, your, you're"
    w "ewes, use, yews"
    w "exercise, exorcise"
    w "eyed, i'd"
    w "eyelet, islet"
    w "eyelets, islets"
    w "facts, fax"
    w "fade, fayed"
    w "faille, file"
    w "fain, feign"
    w "faint, feint"
    w "fainted, feinted"
    w "fainting, feinting"
    w "faints, feints"
    w "fair, fare"
    w "fairies, ferries"
    w "fairs, fares"
    w "fairy, ferry"
    w "faker, fakir"
    w "fakers, fakirs"
    w "farming, pharming"
    w "faro, pharaoh"
    w "fat, phat"
    w "fate, fete"
    w "faun, fawn"
    w "fauns, fawns"
    w "faux, foe"
    w "fay, fey"
    w "faze, phase"
    w "fazed, phased"
    w "fazes, phases"
    w "fazing, phasing"
    w "fear, fere"
    w "feat, feet"
    w "felloe, fellow"
    w "felloes, fellows"
    w "fends, fens"
    w "fiche, fish"
    w "fie, phi"
    w "filer, phylar"
    w "find, fined"
    w "fir, fur"
    w "fern, firn"
    w "ferule, ferrule"
    w "ferules, ferrules"
    w "file, phial"
    w "files, phials"
    w "filter, philtre"
    w "filters, philtres"
    w "find, fined"
    w "firs, furs, furze"
    w "fisher, fissure"
    w "fishers, fissures"
    w "fishing, phishing"
    w "flacks, flax"
    w "flare, flair"
    w "flea, flee"
    w "fleas, flees"
    w "flecks, flex"
    w "flew, flu, flue"
    w "floc, flock"
    w "flocks, phlox"
    w "floe, flow"
    w "floes, flows"
    w "florescent, fluorescent"
    w "flour, flower"
    w "flours, flowers"
    w "flus, flues"
    w "foaled, fold"
    w "4, for, fore, four"
    w "forbear, forebear"
    w "foreword, forward"
    w "fort, forte"
    w "forth, fourth"
    w "foul, fowl"
    w "fouler, fowler"
    w "fouls, fowls"
    w "franc, frank"
    w "francs, franks"
    w "frays, phrase"
    w "frees, freeze, frieze"
    w "freezes, friezes"
    w "friar, fryer"
    w "friars, fryers"
    w "fro, froe"
    w "fungous, fungus"
    w "furs, furze"
    w "gaff, gaffe"
    w "gage, gauge"
    w "gages, gauges"
    w "gait, gate"
    w "gaits, gates"
    w "gamble, gambol"
    w "gambled, gamboled"
    w "gambles, gambols"
    w "gambling, gamboling"
    w "gaud, god"
    w "gauds, gods"
    w "gays, gaze"
    w "genes, jeans"
    w "gibe, jibe"
    w "gilt, guilt"
    w "gin, jinn"
    w "gnu, new, knew"
    w "gnus, news,"
    w "gored, gourd"
    w "graft, graphed"
    w "grate, great"
    w "grater, greater"
    w "grays, graze"
    w "greave, grieve"
    w "greaves, grieves"
    w "grill, grille"
    w "grills, grilles"
    w "grip, grippe"
    w "grisly, grizzly"
    w "groan, grown"
    w "grocer, grosser"
    w "guessed, guest"
    w "guide, guyed"
    w "guise, guys"
    w "hahs, hawse"
    w "hail, hale"
    w "hair, hare"
    w "hairier, harrier"
    w "hairs, hares"
    w "hairy, harry"
    w "hall, haul"
    w "halls, hauls"
    w "halve, have"
    w "halves, haves"
    w "halving, having"
    w "handsome, hansom"
    w "hangar, hanger"
    w "hangars, hangers"
    w "hart, heart"
    w "harts, hearts"
    w "hauler, holler"
    w "hauler, holler"
    w "haulers, hollers"
    w "hawk, hock"
    w "hawks, hocks"
    w "hay, hey"
    w "hays, heys, haze"
    w "heal, heel, he'll"
    w "healed, heeled"
    w "healer, heeler"
    w "healers, heelers"
    w "healing, heeling"
    w "heals, heels"
    w "hear, here"
    w "heard, herd"
    w "hears, here's"
    w "he'd, heed"
    w "herd, hurd"
    w "herds, hurds"
    w "heroin, heroine"
    w "hertz, hurts"
    w "hew, hue"
    w "hews, hues"
    w "hi, hie, high"
    w "higher, hire"
    w "him, hymn"
    w "ho, hoe"
    w "hoar, whore"
    w "hoard, horde"
    w "hoards, hordes"
    w "hoarse, horse"
    w "hoes, hose"
    w "hold, holed"
    w "hole, whole"
    w "holey, holy, wholly"
    w "hoop, whoop"
    w "hoops, whoops"
    w "hostel, hostile"
    w "hour, our"
    w "hours, ours"
    w "house, how's"
    w "humerus, humorous"
    w "idle, idyll"
    w "imminent, immanent"
    w "impassable, impassible"
    w "in, inn"
    w "incidence, incidents"
    w "incite, insight"
    w "indict, indite"
    w "indicted, indited"
    w "indicting, inditing"
    w "innocence, innocents"
    w "ins, inns"
    w "its, it's"
    w "jam, jamb"
    w "jams, jambs"
    w "jewel, joule"
    w "jewels, joules"
    w "kill, kiln"
    w "kills, kilns"
    w "knap, nap"
    w "knave, nave"
    w "knaves, naves"
    w "knead, kneed, need"
    w "kneaded, needed"
    w "kneads, needs"
    w "knight, night"
    w "knights, nights"
    w "knit, nit"
    w "knits, nits"
    w "knob, nob"
    w "knobs, nobs"
    w "knock, nock"
    w "knocks, nocks"
    w "knot, not"
    w "knotty, naughty"
    w "know, no"
    w "knows, noes, nose"
    w "lacks, lax"
    w "lade, laid"
    w "lager, logger"
    w "lagers, loggers"
    w "lain, lane"
    w "lam, lamb"
    w "lama, llama"
    w "lamas, llamas"
    w "laps, lapse"
    w "laser, lazar"
    w "lasers, lazars"
    w "lay, lei, ley"
    w "lays, leis"
    w "lea, lee"
    w "leach, leech"
    w "leaches, leeches"
    w "lead, led"
    w "leak, leek"
    w "leaks, leeks"
    w "lean, lien"
    w "leans, liens"
    w "leas, lees"
    w "leased, least"
    w "leaven, levin"
    w "less, loess"
    w "lessen, lesson"
    w "lessens, lessons"
    w "lesser, lessor"
    w "leucine, loosing"
    w "levee, levy"
    w "levees, levies"
    w "lever, livre"
    w "levers, livres"
    w "liar, lyre"
    w "liars, lyres"
    w "lichen, liken"
    w "lichens, likens"
    w "licker, liquor"
    w "lickers, liquors"
    w "lie, lye"
    w "limb, limn"
    w "limbs, limns"
    w "links, lynx"
    w "lo, low"
    w "load, lode, lowed"
    w "loads, lodes"
    w "loan, lone"
    w "loaner, loner"
    w "loch, lock"
    w "lochs, locks, lox"
    w "loot, lute"
    w "loots, lutes"
    w "luck's, lux"
    w "lumbar, lumber"
    w "ma, maw"
    w "made, maid"
    w "mail, male"
    w "mails, males"
    w "main, mane"
    w "mains, manes"
    w "maize, maze"
    w "mall, maul, moll"
    w "malls, mauls. molls"
    w "mandrel, mandrill"
    w "mandrels, mandrills"
    w "manner, manor"
    w "manners, manors"
    w "marry, merry"
    w "marshal, martial"
    w "martin, marten"
    w "mask, masque"
    w "masks, masques"
    w "massed, mast"
    w "mat, matte"
    w "mean, mien"
    w "meat, meet, mete"
    w "meatier, meteor"
    w "meats, meets"
    w "medal, meddle"
    w "medals, meddles"
    w "metal, mettle"
    w "mews, muse"
    w "mho, mow"
    w "mhos, mows"
    w "might, mite"
    w "mike, mic"
    w "., point, dot"
    w "millenary, millinery"
    w "mince, mints"
    w "mind, mined"
    w "miner, minor"
    w "miners, minors"
    w "minion, minyan"
    w "minks, minx"
    w "miscible, missable"
    w "missal, missile"
    w "missals, missiles"
    w "missed, mist"
    w "misses, mrs., missus"
    w "moan, mown"
    w "moat, mote"
    w "moats, motes"
    w "mock, mach"
    w "mode, mowed"
    w "mood, mooed"
    w "moose, mousse"
    w "mordant, mordent"
    w "mordants, mordents"
    w "morn, mourn"
    w "morning, mourning"
    w "morns, mourns"
    w "mucous, mucus"
    w "murderess, murderous"
    w "murre, myrrh"
    w "muscle, mussel"
    w "muscles, mussels"
    w "mussed, must"
    w "mustard, mustered"
    w "nae, nay, neigh"
    w "naval, navel"
    w "nays, neighs"
    w "neumatic, pneumatic"
    w "nibble, nybble"
    w "nibbles, nybbles"
    w "none, nun"
    w "oar, or, ore"
    w "oars, ores"
    w "ode, owed"
    w "oh, owe"
    w "ohs, owes"
    w "one, won"
    w "oohs, ooze"
    w "paced, paste"
    w "packed, pact"
    w "paid, payed"
    w "pail, pale"
    w "pails, pales"
    w "pain, pane"
    w "pains, panes"
    w "pair, pare, pear"
    w "paired, pared"
    w "pairing, paring"
    w "pairs, pears, pares"
    w "pall, pawl"
    w "pan, panne"
    w "parasite, pericyte"
    w "parasites, pericytes"
    w "parish, perish"
    w "parishes, perishes"
    w "parlay, parley"
    w "parred, pard"
    w "passable, passible"
    w "passed, past"
    w "patience, patients"
    w "pauper, popper"
    w "pause, paws"
    w "pawed, pod"
    w "pawned, pond"
    w "pax, pox"
    w "peace, piece"
    w "peak, peek, pique"
    w "peaked, peeked, piqued"
    w "peaks, peeks, piques"
    w "peal, peel"
    w "pealed, peeled"
    w "pealing, peeling"
    w "peals, peels"
    w "pearl, purl"
    w "pearls, purls"
    w "pedal, peddle"
    w "pedalled, peddled"
    w "pedaller, peddler"
    w "pedalling, peddling"
    w "pedals, peddles"
    w "peer, pier"
    w "peers, piers"
    w "penance, pennants"
    w "pencel, pencil"
    w "pencels, pencils"
    w "people, pipal"
    w "per, purr"
    w "pew , phew, piu"
    w "pi, pie"
    w "pic, pick"
    w "pica, pika"
    w "picas, pikas"
    w "picks, pics, pyx"
    w "picnic, pyknic"
    w "pict, picked"
    w "pidgin, pigeon"
    w "pis, pies"
    w "pistil, pistol"
    w "pistils, pistols"
    w "pixie, pyxie"
    w "plain, plane"
    w "plains, planes"
    w "plait, plate"
    w "plaiter, plater"
    w "plaiters, platers"
    w "plaits, plates"
    w "plantar, planter"
    w "pleas, please"
    w "pleural, plural"
    w "plum, plumb"
    w "plums, plumbs"
    w "pocks, pox"
    w "pole, poll, pull"
    w "poled, polled"
    w "poler, poller"
    w "polers, pollers"
    w "poles, polls, pulls"
    w "pommel, pummel"
    w "populace, populous"
    w "pore, pour, poor"
    w "pored, poured"
    w "pores, pours"
    w "poring, pouring"
    w "praise, prays, preys"
    w "pray, prey"
    w "prayed, preyed"
    w "praying, preying"
    w "precedence, precedents"
    w "premier, premiere"
    w "presence, presents"
    w "presser, pressor"
    w "pressers, pressors"
    w "pride, pried"
    w "prier, prior"
    w "pries, prize"
    w "prince, prints"
    w "principal, principle"
    w "principals, principles"
    w "prise, prys"
    w "profit, prophet"
    w "profits, prophets"
    w "pros, prose"
    w "psychosis, sycosis"
    w "pupal, pupil"
    w "putty, puttee"
    w "puttys, puttees"
    w "quarts, quartz"
    w "quean, queen"
    w "quince, quints"
    w "rack, wrack"
    w "racks, wracks"
    w "rah, raw"
    w "raid, rayed"
    w "rain, reign, rein"
    w "rained, reigned, reined"
    w "rains, reigns, reins"
    w "raise, rays, raze, rase"
    w "raised, razed"
    w "raiser, razer, razor"
    w "raisers, razers, razors"
    w "raises, razes"
    w "raising, razing"
    w "rancor, ranker"
    w "rap, wrap"
    w "rapped, rapt, wrapped"
    w "rapper, wrapper"
    w "rappers, wrappers"
    w "rapping, wrapping"
    w "raps, wraps"
    w "read, red, redd"
    w "read, reed"
    w "reads, reeds"
    w "real, reel"
    w "recite, resite"
    w "recites, resites"
    w "reek, wreak"
    w "reeks, wreaks"
    w "resister, resistor"
    w "rest, wrest"
    w "rests, wrests"
    w "retch, wretch"
    w "review, revue"
    w "reviews, revues"
    w "rheumy, roomy"
    w "rigger, rigor"
    w "riggers, rigors"
    w "right, rite, wright, write"
    w "rights, rites, wrights, writes"
    w "rime, rhyme"
    w "ring, wring"
    w "ringer, wringer"
    w "ringers, wringers"
    w "rings, wrings"
    w "rise, ryes"
    w "road, rode, rowed"
    w "roe, row"
    w "role, roll"
    w "roles, rolls"
    w "roomer, rumor"
    w "roomers, rumors"
    w "root, route"
    w "roots, routes"
    w "rose, rows"
    w "rot, wrought"
    w "rote, wrote"
    w "rued, rude"
    w "rues, ruse"
    w "rum, rhumb"
    w "rung, wrung"
    w "rye, wry"
    w "sac, sack"
    w "sachet, sashay"
    w "sacks, sax"
    w "sail, sale"
    w "sails, sales"
    w "sane, seine"
    w "sari, sorry"
    w "sawed, sod"
    w "scene, seen"
    w "scull, skull"
    w "sculls, skulls"
    w "sea, see, cee"
    w "seal, seel"
    w "seam, seem"
    w "seamed, seemed"
    w "seamen, semen"
    w "seams, seems"
    w "sear, seer, sere"
    w "sears, seers"
    w "seas, sees, seize"
    w "sects, sex"
    w "senate, sennit, sennet"
    w "serf, surf"
    w "serge, surge"
    w "settler, settlor"
    w "settlers, settlors"
    w "sew, so, sow"
    w "sewed, sowed"
    w "sewer, sower"
    w "sewer, suer"
    w "sewn, sown, sone"
    w "sews, sows"
    w "sexed, sext"
    w "sextan, sexton"
    w "shear, sheer"
    w "shears, sheers"
    w "sheave, shiv"
    w "sheaves, shivs"
    w "shivery, shivaree"
    w "shoe, shoo"
    w "shoes, shoos"
    w "shone, shown"
    w "sic, sick"
    w "side, sighed"
    w "sighs, size"
    w "sign, sine, syne"
    w "signet, cygnet"
    w "signs, sines"
    w "sink, sync"
    w "sinking, syncing"
    w "slay, sleigh"
    w "slays, sleighs"
    w "sleave, sleeve"
    w "sleaves, sleeves"
    w "sleight, slight"
    w "slew, slough"
    w "soar, sore"
    w "soared, sword"
    w "soars, sores"
    w "socks, sox"
    w "sole, soul"
    w "soles, souls"
    w "some, sum"
    w "son, sun, sunn"
    w "sonny, sunny"
    w "sons, suns"
    w "sot, sought"
    w "sou, sue"
    w "sous, sues"
    w "spade, spayed"
    w "specks, specs"
    w "spits, spitz"
    w "spoor, spore"
    w "stade, staid, stayed"
    w "staff, staph"
    w "staid, stayed"
    w "stair, stare"
    w "stairs, stares"
    w "stake, steak"
    w "stakes, steaks"
    w "stalk, stock"
    w "stalks, stocks"
    w "stanch, staunch"
    w "stationary, stationery"
    w "steal, steel"
    w "steals, steels"
    w "step, steppe"
    w "steps, steppes"
    w "sticks, styx"
    w "stile, style"
    w "stiles, styles"
    w "stolen, stolon"
    w "stoop, stoup, stupe"
    w "stoops, stoups, stupes"
    w "strait, straight"
    w "succor, sucker"
    w "succors, suckers"
    w "suede, swayed"
    w "suite, sweet"
    w "suites, sweets"
    w "sundae, sunday"
    w "sundaes, sundays"
    w "surplice, surplus"
    w "tacked, tact,"
    w "tacks, tax"
    w "tail, tale"
    w "tails, tales"
    w "talk, tock"
    w "talks, tocks"
    w "taper, tapir"
    w "tapers, tapirs"
    w "tare, tear"
    w "tares, tears"
    w "tarries, terries"
    w "tarry, terry"
    w "taught, tot, taut"
    w "tea, tee"
    w "team, teem"
    w "teams, teems"
    w "tear, tier"
    w "tearrer, terror"
    w "tears, tiers"
    w "teas, tease"
    w "tense, tents"
    w "tern, turn"
    w "terns, turns"
    w "thai, tie"
    w "thais, ties"
    w "their, there, they're"
    w "than, then"
    w "threw, through"
    w "throe, throw"
    w "throes, throws"
    w "throne, thrown"
    w "tic, tick"
    w "tics, ticks"
    w "tied, tide"
    w "tighten, titan"
    w "til, till"
    w "timber, timbre"
    w "timbers, timbers"
    w "time, thyme"
    w "2, to, too, two"
    w "toad, toed, towed"
    w "tocsin, toxin"
    w "tocsins, toxins"
    w "toe, tow"
    w "toes, tows"
    w "told, tolled"
    w "tole, toll"
    w "ton, tun"
    w "tons, tuns"
    w "tool, tulle"
    w "tooter, tutor"
    w "tooters, tutors"
    w "tough, tuff"
    w "toughed, tuft"
    w "tracked, tract"
    w "tracks, tracts"
    w "trade, trayed"
    w "tray, trey"
    w "trays, treys"
    w "troop, troupe"
    w "troops, troupes"
    w "trussed, trust"
    w "turban, turbine"
    w "turbans, turbines"
    w "twill, ‘twill"
    w "undo, undue"
    w "vail, vale, veil"
    w "vain, vane, vein"
    w "vales, veils"
    w "vanes, veins"
    w "vary, very"
    w "vial, vile, viol"
    w "vice, vise"
    w "vices, vises"
    w "villain, villein"
    w "wade, weighed"
    w "wail, wale"
    w "wails, wales"
    w "wain, wane"
    w "waist, waste"
    w "waists, wastes"
    w "wait, weight"
    w "waits, weights"
    w "waive, wave"
    w "waiver, waver"
    w "waivers, wavers"
    w "waives, waves"
    w "walk, wok"
    w "walks, woks"
    w "wand, wanned"
    w "want, wont"
    w "war, wore"
    w "ward, warred"
    w "ware, wear"
    w "wares, wears"
    w "warn, worn"
    w "wart, wort"
    w "warts, worts"
    w "way, weigh"
    w "we, wee"
    w "weed, we'd"
    w "weak, week"
    w "whether, weather"
    w "weakly, weekly"
    w "weal, we'll, wheel"
    w "wean, ween"
    w "weather, wether"
    w "weave, we've"
    w "we'd, weed"
    w "weighs, ways"
    w "we're, weir"
    w "wheal, wheel"
    w "wheals, wheels"
    w "wind, wined"
    w "wood, would"
    w "yawn, yon"
    w "yoke, yolk"
    w "yokes, yolks"
    w "you'll, yule"
    w "you're, yore, your"
  ]
Homonyms.initialize()