@CommandoSettings = 
  defaultBrowser: "Chrome"
  websites:
    amazon: "amazon.com"
    "amazon console": "console.aws.amazon.com"
    atmosphere: "atmospherejs.com"
    balsamic: "www.mybalsamiq.com/login"
    chase: "chase.com"
    "cloudflare": "www.cloudflare.com"
    "craigslist": "craigslist.com"
    "github": "github.com"
    gmail: "mail.google.com"
    "google docs": "docs.google.com"
    heroku: "heroku.com"
    "modulus": "modulus.io/user/dashboard"
    "mongo hq": "app.mongohq.com/databases"
  applications:
    term: "iTerm"
    web: "Chrome"
    chrome: "Chrome"
    sky: "Skype"
    billy: "Adobe Illustrator"
    shop: "Adobe Photoshop CC 2014"
    calendar: "Calendar"
    drag: "Dragon Dictate"
    find: "Path Finder"
    logic: "Logic Pro X"
    mail: "Mail"
    message: "Messages"
    pass: "1Password"
    page: "Pages"
    robo: "Robomongo"
    system: "System Preferences"
    tree: "SourceTree"
    tune: "iTunes"
    preview: "Preview"
    sublime: "Sublime Text"