module.exports = [
  "acclamation, acclimation"
  "acts, ax"
  "ad, add"
  "ade, aid, aide"
  "ades, aids, aides"
  "adherence, adherents"
  "adieu, ado"
  "admittance, admittants"
  "adolescence, adolescents"
  "ads, adds, adz"
  "aerie, airy"
  "aero, arrow"
  "agar, auger, augur"
  "agars, augers, augurs"
  "ail, ale"
  "ails, ales"
  "air, ere, heir"
  "airs, heirs"
  "I'll, aisle, isle, awl, all"
  "allowed, aloud"
  "all's, awls"
  "altar, alter"
  "altars, alters"
  "analyst, annalist"
  "analysts, annalists"
  "ant, aunt"
  "ants, aunts"
  "ante, anti, aunty"
  "apatite, appetite"
  "append, upend"
  "appended, upended"
  "appending, upending"
  "arc, ark"
  "arcs, arks"
  "are, our, hour"
  "arrant, errant"
  "ascent, assent"
  "ascents, assents"
  "assistance, assistants"
  "ate, eight"
  "attendance, attendants"
  "aught, ought"
  "auks, ox"
  "aural, oral"
  "aureole, oriole"
  "aureoles, orioles"
  "auricle, oracle"
  "auricles, oracles"
  "auxin, oxen"
  "away, aweigh"
  "awed, odd"
  "awes, os"
  "awful, offal"
  "awn, on"
  "axel, axil, axle"
  "axes, axis"
  "aye , eye, i"
  "ayes, eyes"
  "baa, bah"
  "bad, bade"
  "baal, bail, bale"
  "bailer, baler"
  "bailers, balers"
  "bailing, baling"
  "bails, bales"
  "bait, bate"
  "baited, bated"
  "baits, bates"
  "baize, bays"
  "bald, balled, bawled"
  "balks, box"
  "ball, bawl"
  "balls, bawls"
  "balm, bomb"
  "balms, bombs"
  "baloney, bologna"
  "band, banned"
  "bans, banns, bands"
  "bar, barre"
  "bard, barred"
  "bare, bear"
  "bares, bears"
  "baring, bearing"
  "baron, barren"
  "barrel, beryl"
  "base, bass"
  "based, baste"
  "basis, basses"
  "bask, basque"
  "basks, basques"
  "bate, bait"
  "bated, baited"
  "bates, baits"
  "bauble, bobble"
  "baubles, bobbles"
  "baud, bawd"
  "bawdy, body"
  "bay, bey"
  "bazaar, bizarre"
  "be, bee"
  "beach, beech"
  "beaches, beeches"
  "beat, beet"
  "beats, beets"
  "beau, bow"
  "beaus, bows"
  "been, bin"
  "beer, bier"
  "beers, biers"
  "beetle, betel"
  "bees, bise"
  "belligerence, belligerents"
  "bell, belle"
  "bells, belles"
  "berg, burg"
  "bergs, burgs"
  "berries, buries"
  "berry, bury"
  "berth, birth"
  "berthed, birthed"
  "berthing, birthing"
  "berths, births"
  "better, bettor"
  "bib, bibb"
  "bibs, bibbs"
  "bight, bite, byte"
  "bights, bites, bytes"
  "billed, build"
  "bird, burred"
  "birr, burr"
  "bit, bitt"
  "bits, bitts"
  "blend, blende"
  "blends, blendes"
  "blew, blue"
  "bloc, block"
  "blocs, blocks"
  "blond, blonde"
  "boar, bore"
  "board, bored"
  "boarder, border"
  "boarders, borders"
  "boars, bores"
  "bode, bowed"
  "bodies, body's"
  "bogie, bogey, bogy"
  "bold, bowled"
  "bolder, boulder"
  "bole, boll, bowl"
  "boles, bolls, bowls"
  "boos, booze"
  "bootie, booty"
  "born, bourn"
  "borough, burro, burrow"
  "boroughs, burros, burrows"
  "bouillon, bullion"
  "bow, bough"
  "bows, boughs"
  "brae, bray"
  "braid, brayed"
  "braille, brale"
  "braise, brays, braze"
  "brake, break"
  "brakes, breaks"
  "braking, breaking"
  "breach, breech"
  "breaches, breeches"
  "bread, bred"
  "brede, breed,"
  "bredes, breeds"
  "brewed, brood"
  "brews, bruise"
  "bridal, bridle"
  "broach, brooch"
  "broom, brougham"
  "brooms, broughams"
  "browse, brows"
  "bruit, brute"
  "buccal, buckle"
  "burger, burgher"
  "burgers, burghers"
  "bus , buss"
  "buses, busses"
  "bussed, bust"
  "but, butt"
  "buts, butts"
  "buy, by, bye"
  "buyer, byer"
  "buyers, byers"
  "buys, byes"
  "cache, cash"
  "cached, cashed"
  "caches, cashes"
  "caching, cashing"
  "cachou , cashew"
  "cachous, cashews"
  "calendar, calender"
  "calendars, calenders"
  "calix, calyx"
  "calixes, calyxes"
  "calk, caulk"
  "calks, caulks"
  "call, caul"
  "caller, choler, collar"
  "callers, collars"
  "cannon, canon"
  "cannons, canons"
  "cant, can't"
  "canter, cantor"
  "canters, cantors"
  "canvas, canvass"
  "canvases, canvasses"
  "capital, capitol"
  "capitals, capitols"
  "caret, carrot, karat"
  "carets, carrots, karats"
  "caries, carries"
  "carol, carrel"
  "carols, carrels"
  "cart, kart"
  "carts, karts"
  "cask, casque"
  "casks, casques"
  "cast, caste"
  "caster, castor"
  "casters, castors"
  "casts, castes"
  "catch, ketch"
  "catches, ketches"
  "cat'll, cattle"
  "caudal, caudle, coddle"
  "cause, caws"
  "cawed, cod"
  "cedar, seeder"
  "cedars, seeders"
  "cede, seed"
  "ceded, seeded"
  "cedes, seeds"
  "ceding, seeding"
  "ceil, seal, seel"
  "ceils, seals, seels"
  "ceiling, sealing"
  "ceilings, sealings"
  "cell, sell"
  "cellar, seller"
  "cellars, sellers"
  "cellar's, seller's"
  "cells, sells"
  "cense, cents, scents, sense"
  "censers, censors, sensors"
  "census, senses"
  "cent, scent, sent"
  "cents, sense"
  "centuries, century's"
  "cere, sear, seer, sere"
  "ceres, sears, seers, seres"
  "cereal, serial"
  "cereals, serials"
  "cession, session"
  "cessions, sessions"
  "chalk, chock"
  "chalks, chocks"
  "chance, chants"
  "chanty, shanty"
  "chantys, shantys"
  "chard, charred"
  "chary, cherry"
  "chased, chaste"
  "cheap, cheep"
  "check, cheque, czech"
  "checks, cheques, czechs"
  "chews, choose"
  "chic, sheik"
  "chili, chilly"
  "chitin, chiton"
  "choir, quire"
  "choirs, quires"
  "choral, coral"
  "chorale, corral"
  "chorales, corrals"
  "chord, cord, cored"
  "chordate, cordate"
  "chords, cords"
  "chott, shot"
  "chotts, shots"
  "chough, chuff"
  "choughs, chuffs"
  "chrism, chrisom"
  "chucker, chukker"
  "chuckers, chukkers"
  "chute, shoot"
  "chutes, shoots"
  "cingular, singular"
  "cirrus, serous"
  "cist, cyst"
  "cists, cysts"
  "citable, sightable"
  "cite, sight, site"
  "cited, sighted, sited"
  "cites, sights, sites"
  "citing, sighting, siting"
  "clack, claque"
  "clacks, claques"
  "claimant, clamant"
  "claimants, clamants"
  "clause, claws"
  "clawed, clod"
  "clew, clue"
  "clews, clues"
  "click, clique, klick"
  "clicks, cliques, klicks"
  "climb, clime"
  "climbs, climes"
  "close, clothes"
  "coal, cole, kohl"
  "coarse, corse, course"
  "coat, cote"
  "coats, cotes"
  "coax, cokes"
  "cocks, cox"
  "coffer, cougher"
  "coffers, coughers"
  "coin, quoin"
  "coins, quoins"
  "collared, collard"
  "colonel, kernel"
  "colonels, colonel's, kernels"
  "competence, competents"
  "complacent, complaisant"
  "complement, compliment"
  "complementary, complimentary"
  "complemented, complimented"
  "complementing, complimenting"
  "concord, conquered"
  "confectionary, confectionery"
  "conk, conch"
  "conks, conchs"
  "coo, coup"
  "coop, coupe"
  "coops, coupes"
  "coos, coups"
  "cops, copse"
  "coquet, coquette"
  "cord, cored"
  "core, corps"
  "correspondence, correspondents"
  "cosign, cosine"
  "cosigns, cosines"
  "council, counsel"
  "councils, counsels"
  "councillor, counselor"
  "councillors, counselors"
  "cousin, cozen"
  "cousins, cozens"
  "coward, cowered, cowherd"
  "craft, kraft"
  "crape, crepe"
  "crapes, crepes"
  "crater, krater"
  "craters, kraters"
  "crawl, kraal"
  "crawls, kraals"
  "creak, creek"
  "creaks, creeks"
  "crewel, cruel"
  "crews, cruise, cruse"
  "crows, croze"
  "crude, crewed"
  "cue, queue"
  "cues, queues"
  "currant, current"
  "currants, currents"
  "curser, cursor"
  "cursers, cursors"
  "cygnet, signet"
  "cygnets, signets"
  "cymbal, symbol"
  "cymbals, symbols"
  "dam, damn"
  "dammed, damned"
  "damming, damning"
  "dams, damns"
  "dane , deign"
  "danes, deigns"
  "dawn, don"
  "dawns, dons"
  "days, daze"
  "dean, dene"
  "deans, dene"
  "dear, deer"
  "deem, deme"
  "deems, demes"
  "defuse, diffuse"
  "delinquence, delinquents"
  "dense, dents"
  "descent, dissent"
  "dental, dentil"
  "dependence, dependents"
  "depravation, deprivation"
  "depravations, deprivations"
  "descent, dissent"
  "descents, dissents"
  "deviance, deviants"
  "devisor, divisor"
  "devisors, divisors"
  "dew, do, due"
  "dewed, dude"
  "dewing, doing"
  "dews, dues"
  "die, dye"
  "died, dyed"
  "dies, dyes"
  "dine, dyne"
  "dines, dynes"
  "dire, dyer"
  "disburse, disperse"
  "disburses, disperses"
  "discreet, discrete"
  "discussed, disgust"
  "dissidence, dissidents"
  "djinn, gin"
  "do doe, dough"
  "doc, dock"
  "docs, docks"
  "doe, dough"
  "doer, dour"
  "does, doze, doughs"
  "doing, dewing"
  "done, dun"
  "dos, dues"
  "dost, dust"
  "douse, dowse"
  "droop, drupe"
  "droops, drupes"
  "dual, duel"
  "duals, duels"
  "ducked, duct"
  "dyeing, dying"
  "earn, erne, urn"
  "earns, ernes, urns"
  "eave, eve"
  "eaves, eves"
  "eek, eke"
  "eeks, ekes"
  "eerie, erie"
  "elicit, illicit"
  "elude, allude"
  "eludes, alludes"
  "emerge, immerge"
  "emerged, immerged"
  "emerges, immerges"
  "emerging, immerging"
  "encyst, insist"
  "encysts, insists"
  "enfold, infold"
  "enfolds, infolds"
  "ensure, insure"
  "ensure, insuring"
  "ensured, insured"
  "ensuring, insures"
  "epic, epoch"
  "epics, epochs"
  "equivalence, equivalents"
  "erupt, irrupt"
  "eruption, irruption"
  "eruptions, irruptions"
  "eruptive, irruptive"
  "eruptively, irruptively"
  "ewe, yew, you"
  "ewer, your, you're"
  "ewes, use, yews"
  "exercise, exorcise"
  "eyed, i'd"
  "eyelet, islet"
  "eyelets, islets"
  "facts, fax"
  "fade, fayed"
  "faille, file"
  "fain, feign"
  "faint, feint"
  "fainted, feinted"
  "fainting, feinting"
  "faints, feints"
  "fair, fare"
  "fairies, ferries"
  "fairs, fares"
  "fairy, ferry"
  "faker, fakir"
  "fakers, fakirs"
  "farming, pharming"
  "faro, pharaoh"
  "fat, phat"
  "fate, fete"
  "faun, fawn"
  "fauns, fawns"
  "faux, foe"
  "fay, fey"
  "faze, phase"
  "fazed, phased"
  "fazes, phases"
  "fazing, phasing"
  "fear, fere"
  "feat, feet"
  "felloe, fellow"
  "felloes, fellows"
  "fends, fens"
  "fiche, fish"
  "fie, phi"
  "filer, phylar"
  "find, fined"
  "fir, fur"
  "fern, firn"
  "ferule, ferrule"
  "ferules, ferrules"
  "file, phial"
  "files, phials"
  "filter, philtre"
  "filters, philtres"
  "find, fined"
  "firs, furs, furze"
  "fisher, fissure"
  "fishers, fissures"
  "fishing, phishing"
  "flacks, flax"
  "flare, flair"
  "flea, flee"
  "fleas, flees"
  "flecks, flex"
  "flew, flu, flue"
  "floc, flock"
  "flocks, phlox"
  "floe, flow"
  "floes, flows"
  "florescent, fluorescent"
  "flour, flower"
  "flours, flowers"
  "flus, flues"
  "foaled, fold"
  "4, for, fore, four"
  "forbear, forebear"
  "foreword, forward"
  "fort, forte"
  "forth, fourth"
  "foul, fowl"
  "fouler, fowler"
  "fouls, fowls"
  "franc, frank"
  "francs, franks"
  "frays, phrase"
  "frees, freeze, frieze"
  "freezes, friezes"
  "friar, fryer"
  "friars, fryers"
  "fro, froe"
  "fungous, fungus"
  "furs, furze"
  "gaff, gaffe"
  "gage, gauge"
  "gages, gauges"
  "gait, gate"
  "gaits, gates"
  "gamble, gambol"
  "gambled, gamboled"
  "gambles, gambols"
  "gambling, gamboling"
  "gaud, god"
  "gauds, gods"
  "gays, gaze"
  "gene, jean"
  "genes, jeans"
  "gibe, jibe"
  "gilt, guilt"
  "gin, jinn"
  "gnu, new, knew"
  "gnus, news,"
  "gored, gourd"
  "graft, graphed"
  "grate, great"
  "grater, greater"
  "grays, graze"
  "greave, grieve"
  "greaves, grieves"
  "grill, grille"
  "grills, grilles"
  "grip, grippe"
  "grisly, grizzly"
  "groan, grown"
  "grocer, grosser"
  "guessed, guest"
  "guide, guyed"
  "guise, guys"
  "hahs, hawse"
  "hail, hale"
  "hair, hare"
  "hairier, harrier"
  "hairs, hares"
  "hairy, harry"
  "hall, haul"
  "halls, hauls"
  "halve, have"
  "halves, haves"
  "halving, having"
  "handsome, hansom"
  "hangar, hanger"
  "hangars, hangers"
  "hart, heart"
  "harts, hearts"
  "hauler, holler"
  "hauler, holler"
  "haulers, hollers"
  "hawk, hock"
  "hawks, hocks"
  "hay, hey"
  "hays, heys, haze"
  "heal, heel, he'll"
  "healed, heeled"
  "healer, heeler"
  "healers, heelers"
  "healing, heeling"
  "heals, heels"
  "hear, here"
  "heard, herd"
  "hears, here's"
  "he'd, heed"
  "herd, hurd"
  "herds, hurds"
  "heroin, heroine"
  "hertz, hurts"
  "hew, hue"
  "hews, hues"
  "hi, hie, high"
  "higher, hire"
  "him, hymn"
  "ho, hoe"
  "hoar, whore"
  "hoard, horde"
  "hoards, hordes"
  "hoarse, horse"
  "hoes, hose"
  "hold, holed"
  "hole, whole"
  "holey, holy, wholly"
  "hoop, whoop"
  "hoops, whoops"
  "hostel, hostile"
  "hour, our"
  "hours, ours"
  "house, how's"
  "humerus, humorous"
  "idle, idyll"
  "imminent, immanent"
  "impassable, impassible"
  "in, inn"
  "incidence, incidents"
  "incite, insight"
  "indict, indite"
  "indicted, indited"
  "indicting, inditing"
  "innocence, innocents"
  "ins, inns"
  "its, it's"
  "jam, jamb"
  "jams, jambs"
  "jewel, joule"
  "jewels, joules"
  "kill, kiln"
  "kills, kilns"
  "knap, nap"
  "knave, nave"
  "knaves, naves"
  "knead, kneed, need"
  "kneaded, needed"
  "kneads, needs"
  "knight, night"
  "knights, nights"
  "knit, nit"
  "knits, nits"
  "knob, nob"
  "knobs, nobs"
  "knock, nock"
  "knocks, nocks"
  "knot, not"
  "knotty, naughty"
  "know, no"
  "knows, noes, nose"
  "lacks, lax"
  "lade, laid"
  "lager, logger"
  "lagers, loggers"
  "lain, lane"
  "lam, lamb"
  "lama, llama"
  "lamas, llamas"
  "laps, lapse"
  "laser, lazar"
  "lasers, lazars"
  "lay, lei, ley"
  "lays, leis"
  "lea, lee"
  "leach, leech"
  "leaches, leeches"
  "lead, led"
  "leak, leek"
  "leaks, leeks"
  "lean, lien"
  "leans, liens"
  "leas, lees"
  "leased, least"
  "leaven, levin"
  "less, loess"
  "lessen, lesson"
  "lessens, lessons"
  "lesser, lessor"
  "leucine, loosing"
  "levee, levy"
  "levees, levies"
  "lever, livre"
  "levers, livres"
  "liar, lyre"
  "light, lite"
  "liars, lyres"
  "lichen, liken"
  "lichens, likens"
  "licker, liquor"
  "lickers, liquors"
  "lie, lye"
  "limb, limn"
  "limbs, limns"
  "links, lynx"
  "lo, low"
  "load, lode, lowed"
  "loads, lodes"
  "loan, lone"
  "loaner, loner"
  "loch, lock"
  "lochs, locks, lox"
  "loot, lute"
  "loots, lutes"
  "luck's, lux"
  "lumbar, lumber"
  "ma, maw"
  "made, maid"
  "mail, male"
  "mails, males"
  "main, mane"
  "mains, manes"
  "maize, maze"
  "mall, maul, moll"
  "malls, mauls. molls"
  "mandrel, mandrill"
  "mandrels, mandrills"
  "manner, manor"
  "manners, manors"
  "marry, merry"
  "marshal, martial"
  "martin, marten"
  "mask, masque"
  "masks, masques"
  "massed, mast"
  "mat, matte"
  "mean, mien"
  "meat, meet, mete"
  "meatier, meteor"
  "meats, meets"
  "medal, meddle"
  "medals, meddles"
  "metal, mettle"
  "mews, muse"
  "mho, mow"
  "mhos, mows"
  "might, mite"
  "mike, mic"
  "., point, dot"
  "millenary, millinery"
  "mince, mints"
  "mind, mined"
  "miner, minor"
  "miners, minors"
  "minion, minyan"
  "minks, minx"
  "miscible, missable"
  "missal, missile"
  "missals, missiles"
  "missed, mist"
  "misses, mrs., missus"
  "moan, mown"
  "moat, mote"
  "moats, motes"
  "mock, mach"
  "mode, mowed"
  "mood, mooed"
  "moose, mousse"
  "mordant, mordent"
  "mordants, mordents"
  "morn, mourn"
  "morning, mourning"
  "morns, mourns"
  "mucous, mucus"
  "murderess, murderous"
  "murre, myrrh"
  "muscle, mussel"
  "muscles, mussels"
  "mussed, must"
  "mustard, mustered"
  "nae, nay, neigh"
  "naval, navel"
  "nays, neighs"
  "neumatic, pneumatic"
  "nibble, nybble"
  "nibbles, nybbles"
  "none, nun"
  "oar, or, ore"
  "oars, ores"
  "ode, owed"
  "oh, owe"
  "ohs, owes"
  "1, won, one"
  "oohs, ooze"
  "paced, paste"
  "packed, pact"
  "paid, payed"
  "pail, pale"
  "pails, pales"
  "pain, pane"
  "pains, panes"
  "pair, pare, pear"
  "paired, pared"
  "pairing, paring"
  "pairs, pears, pares"
  "pall, pawl"
  "pan, panne"
  "parasite, pericyte"
  "parasites, pericytes"
  "parish, perish"
  "parishes, perishes"
  "parlay, parley"
  "parred, pard"
  "passable, passible"
  "passed, past"
  "patience, patients"
  "pauper, popper"
  "pause, paws"
  "pawed, pod"
  "pawned, pond"
  "pax, pox"
  "peace, piece"
  "peak, peek, pique"
  "peaked, peeked, piqued"
  "peaks, peeks, piques"
  "peal, peel"
  "pealed, peeled"
  "pealing, peeling"
  "peals, peels"
  "pearl, purl"
  "pearls, purls"
  "pedal, peddle"
  "pedalled, peddled"
  "pedaller, peddler"
  "pedalling, peddling"
  "pedals, peddles"
  "peer, pier"
  "peers, piers"
  "penance, pennants"
  "pencel, pencil"
  "pencels, pencils"
  "people, pipal"
  "per, purr"
  "pew , phew, piu"
  "pi, pie"
  "pic, pick"
  "pica, pika"
  "picas, pikas"
  "picks, pics, pyx"
  "picnic, pyknic"
  "pict, picked"
  "pidgin, pigeon"
  "pis, pies"
  "pistil, pistol"
  "pistils, pistols"
  "pixie, pyxie"
  "plain, plane"
  "plains, planes"
  "plait, plate"
  "plaiter, plater"
  "plaiters, platers"
  "plaits, plates"
  "plantar, planter"
  "pleas, please"
  "pleural, plural"
  "plum, plumb"
  "plums, plumbs"
  "pocks, pox"
  "pole, poll, pull, pool"
  "poled, polled"
  "poler, poller"
  "polers, pollers"
  "poles, polls, pulls"
  "pommel, pummel"
  "populace, populous"
  "pore, pour, poor"
  "pored, poured"
  "pores, pours"
  "poring, pouring"
  "praise, prays, preys"
  "pray, prey"
  "prayed, preyed"
  "praying, preying"
  "precedence, precedents"
  "premier, premiere"
  "presence, presents"
  "presser, pressor"
  "pressers, pressors"
  "pride, pried"
  "prier, prior"
  "pries, prize"
  "prince, prints"
  "principal, principle"
  "principals, principles"
  "prise, prys"
  "profit, prophet"
  "profits, prophets"
  "pros, prose"
  "psychosis, sycosis"
  "pupal, pupil"
  "putty, puttee"
  "puttys, puttees"
  "quarts, quartz"
  "quean, queen"
  "quince, quints"
  "rack, wrack"
  "racks, wracks"
  "rah, raw"
  "raid, rayed"
  "rain, reign, rein"
  "rained, reigned, reined"
  "rains, reigns, reins"
  "raise, rays, raze, rase"
  "raised, razed"
  "raiser, razer, razor"
  "raisers, razers, razors"
  "raises, razes"
  "raising, razing"
  "rancor, ranker"
  "rap, wrap"
  "rapped, rapt, wrapped"
  "rapper, wrapper"
  "rappers, wrappers"
  "rapping, wrapping"
  "raps, wraps"
  "read, red, redd"
  "read, reed"
  "reads, reeds"
  "real, reel"
  "recite, resite"
  "recites, resites"
  "reek, wreak"
  "reeks, wreaks"
  "resister, resistor"
  "rest, wrest"
  "rests, wrests"
  "retch, wretch"
  "review, revue"
  "reviews, revues"
  "rheumy, roomy"
  "rigger, rigor"
  "riggers, rigors"
  "right, rite, wright, write"
  "rights, rites, wrights, writes"
  "rime, rhyme"
  "ring, wring"
  "ringer, wringer"
  "ringers, wringers"
  "rings, wrings"
  "rise, ryes"
  "road, rode, rowed"
  "roe, row"
  "role, roll"
  "roles, rolls"
  "roomer, rumor"
  "roomers, rumors"
  "root, route"
  "roots, routes"
  "rose, rows"
  "rot, wrought"
  "rote, wrote"
  "rued, rude"
  "rues, ruse"
  "rum, rhumb"
  "rung, wrung"
  "rye, wry"
  "sac, sack"
  "sachet, sashay"
  "sacks, sax"
  "sail, sale"
  "sails, sales"
  "sane, seine"
  "sari, sorry"
  "sawed, sod"
  "scene, seen"
  "scull, skull"
  "sculls, skulls"
  "sea, see, cee"
  "seal, seel"
  "seam, seem"
  "sean, shawn"
  "seamed, seemed"
  "seamen, semen"
  "seams, seems"
  "sear, seer, sere"
  "sears, seers"
  "seas, sees, seize"
  "sects, sex"
  "senate, sennit, sennet"
  "serf, surf"
  "serge, surge"
  "settler, settlor"
  "settlers, settlors"
  "sew, so, sow"
  "sewed, sowed"
  "sewer, sower"
  "sewer, suer"
  "sewn, sown, sone"
  "sews, sows"
  "sexed, sext"
  "sextan, sexton"
  "shear, sheer"
  "shears, sheers"
  "sheave, shiv"
  "sheaves, shivs"
  "shivery, shivaree"
  "shoe, shoo"
  "shoes, shoos"
  "shone, shown"
  "sic, sick"
  "side, sighed"
  "sighs, size"
  "sign, sine, syne"
  "signet, cygnet"
  "signs, sines"
  "sink, sync"
  "sinking, syncing"
  "slay, sleigh"
  "slays, sleighs"
  "sleave, sleeve"
  "sleaves, sleeves"
  "sleight, slight"
  "slew, slough"
  "soar, sore"
  "soared, sword"
  "soars, sores"
  "socks, sox"
  "sole, soul"
  "soles, souls"
  "some, sum"
  "son, sun, sunn"
  "sonny, sunny"
  "sons, suns"
  "sot, sought"
  "sou, sue"
  "sous, sues"
  "spade, spayed"
  "specks, specs"
  "spits, spitz"
  "spoor, spore"
  "stade, staid, stayed"
  "staff, staph"
  "staid, stayed"
  "stair, stare"
  "stairs, stares"
  "stake, steak"
  "stakes, steaks"
  "stalk, stock"
  "stalks, stocks"
  "stanch, staunch"
  "stationary, stationery"
  "steal, steel"
  "steals, steels"
  "step, steppe"
  "steps, steppes"
  "sticks, styx"
  "stile, style"
  "stiles, styles"
  "stolen, stolon"
  "stoop, stoup, stupe"
  "stoops, stoups, stupes"
  "strait, straight"
  "succor, sucker"
  "succors, suckers"
  "suede, swayed"
  "suite, sweet"
  "suites, sweets"
  "sundae, sunday"
  "sundaes, sundays"
  "surplice, surplus"
  "tacked, tact,"
  "tacks, tax"
  "tail, tale"
  "tails, tales"
  "talk, tock"
  "talks, tocks"
  "taper, tapir"
  "tapers, tapirs"
  "tare, tear"
  "tares, tears"
  "tarries, terries"
  "tarry, terry"
  "taught, tot, taut"
  "tea, tee"
  "team, teem"
  "teams, teems"
  "tear, tier"
  "tearrer, terror"
  "tears, tiers"
  "teas, tease"
  "tense, tents"
  "tern, turn"
  "terns, turns"
  "thai, tie"
  "thais, ties"
  "their, there, they're"
  "than, then"
  "threw, through"
  "throe, throw"
  "throes, throws"
  "throne, thrown"
  "tic, tick"
  "tics, ticks"
  "tied, tide"
  "tighten, titan"
  "til, till"
  "timber, timbre"
  "timbers, timbers"
  "time, thyme"
  "2, to, too, two"
  "toad, toed, towed"
  "tocsin, toxin"
  "tocsins, toxins"
  "toe, tow"
  "toes, tows"
  "told, tolled"
  "tole, toll"
  "ton, tun"
  "tons, tuns"
  "tool, tulle"
  "tooter, tutor"
  "tooters, tutors"
  "tough, tuff"
  "toughed, tuft"
  "tracked, tract"
  "tracks, tracts"
  "trade, trayed"
  "tray, trey"
  "trays, treys"
  "troop, troupe"
  "troops, troupes"
  "trussed, trust"
  "turban, turbine"
  "turbans, turbines"
  "twill, ‘twill"
  "undo, undue"
  "vail, vale, veil"
  "vain, vane, vein"
  "vales, veils"
  "vanes, veins"
  "vary, very"
  "vial, vile, viol"
  "vice, vise"
  "vices, vises"
  "villain, villein"
  "wade, weighed"
  "wail, wale"
  "wails, wales"
  "wain, wane"
  "waist, waste"
  "waists, wastes"
  "wait, weight"
  "waits, weights"
  "waive, wave"
  "waiver, waver"
  "waivers, wavers"
  "waives, waves"
  "walk, wok"
  "walks, woks"
  "wand, wanned"
  "want, wont"
  "war, wore"
  "ward, warred"
  "ware, wear"
  "wares, wears"
  "warn, worn"
  "wart, wort"
  "warts, worts"
  "way, weigh"
  "we, wee"
  "weed, we'd"
  "weak, week"
  "whether, weather, wether"
  "weakly, weekly"
  "weal, we'll, wheel"
  "wean, ween"
  "weave, we've"
  "we'd, weed"
  "weighs, ways"
  "we're, weir"
  "wheal, wheel"
  "wheals, wheels"
  "wind, wined"
  "wood, would"
  "yawn, yon"
  "yoke, yolk"
  "yokes, yolks"
  "you'll, yule"
  "you're, yore, your"
]
